version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "19999:80"
    volumes:
      - /Users/yh/www:/www
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
