services:
  nats:
    image: nats
    ports:
      - 4222:4222
  etcd:
    image: bitnami/etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
  redis:
    image: redis:latest
    container_name: redis_6378
    ports:
      - "6378:6378"
    volumes:
      - ./redis_data:/data
    command: redis-server --save 900 1 --save 300 10 --save 60 10000
    restart: unless-stopped
