// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Net_Match3.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Pb
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_Match3Info : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Base_Match3_RoomInfo RoomInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_RoomInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int RoomId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int RoomTypeId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int RoomStatus { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long CurrentServerTime { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long StartTime { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public long EndTime { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int CountdownNum { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int ChairMaxNum { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, Base_Match3_RoleInfo> RoleList { get; set; } = new global::System.Collections.Generic.Dictionary<int, Base_Match3_RoleInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_SetChesses : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, Base_Match3_Chess> ChangeChesses { get; set; } = new global::System.Collections.Generic.Dictionary<int, Base_Match3_Chess>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_ChessboardInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int MoveType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int BeginPos { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int EndPos { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int SkillId { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, Base_Match3_RepeatInt> FirstEliminated { get; set; } = new global::System.Collections.Generic.Dictionary<int, Base_Match3_RepeatInt>();

        [global::ProtoBuf.ProtoMember(6)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, Base_Match3_RepeatInt> NextEliminated { get; set; } = new global::System.Collections.Generic.Dictionary<int, Base_Match3_RepeatInt>();

        [global::ProtoBuf.ProtoMember(7)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, Base_Match3_SupplyChesses> SupplyChesses { get; set; } = new global::System.Collections.Generic.Dictionary<int, Base_Match3_SupplyChesses>();

        [global::ProtoBuf.ProtoMember(8)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, Base_Match3_Chess> ChessGrid { get; set; } = new global::System.Collections.Generic.Dictionary<int, Base_Match3_Chess>();

        [global::ProtoBuf.ProtoMember(9)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, Base_Match3_Chess> ChangeChesses { get; set; } = new global::System.Collections.Generic.Dictionary<int, Base_Match3_Chess>();

        [global::ProtoBuf.ProtoMember(10)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, Base_Match3_SetChesses> TargetChangeChesses { get; set; } = new global::System.Collections.Generic.Dictionary<int, Base_Match3_SetChesses>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_HeroInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int Hp { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int HpLimit { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int Atk { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int Step { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int RecoveryTime { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int HeadIconId { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int Quality { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Detect { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Skill { get; set; } = "";

        [global::ProtoBuf.ProtoMember(13)]
        public int Buy { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_SkillBarInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Base_Match3_ChessboardSkillInfo ChessboardSkill1 { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Base_Match3_ChessboardSkillInfo ChessboardSkill2 { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Base_Match3_ChessboardSkillInfo ChessboardSkill3 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_ChessboardSkillInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public int ClearType { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int Point { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int ActiveColor { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int ActiveNum { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int BoardSkillIId { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue("")]
        public string SkillIcon { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string BottomFrame { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11)]
        public int EffectsKillok { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public int DelayTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_HeroSkillInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, Base_Match3_HeroSkillItemInfo> HeroSkillItemList { get; set; } = new global::System.Collections.Generic.Dictionary<string, Base_Match3_HeroSkillItemInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_HeroSkillItemInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int TargetType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_HeroAttackInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_RoleInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int ChairId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string NickName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public bool IsOnline { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool IsAIRobot { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string BindPlayerId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public bool IsOwner { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int SelectHeroId { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public Base_Match3_HeroInfo HeroInfo { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public Base_Match3_SkillBarInfo SkillBarInfo { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public Base_Match3_ChessboardInfo ChessboardInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_RepeatInt : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public int[] IntList { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_SimpleChess : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int ChessColor { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int SpeType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_Chess : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int ChessId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int ChessColor { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int SubChessId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int FrozenCnt { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long ExpireTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_SupplyChesses : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Base_Match3_SimpleChess> SupplyChesses { get; set; } = new global::System.Collections.Generic.List<Base_Match3_SimpleChess>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_JieSuanRoleInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int RankingNum { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int ChairId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string NickName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> RewardItemList { get; set; } = new global::System.Collections.Generic.Dictionary<int, int>();

        [global::ProtoBuf.ProtoMember(6)]
        public bool IsWin { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_InterfereInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string FromRoleId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<string> DstRoleId { get; set; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3)]
        public int InterfereType { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsPacked = true)]
        public int[] InterfereKeys { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int SkillEnergyDt { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int BlessingEnergyDt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_InterfereReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Base_Match3_InterfereInfo InterfereInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_InterfereRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Base_Match3_InterfereInfo InterfereInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_StartMatchingRoomReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int RoomTypeId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int SelectHeroId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_StartMatchingRoomRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Ret { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_CancelMatchingReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_CancelMatchingRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Ret { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_OtherRoleEnterRoomRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Base_Match3_RoleInfo OtherRole { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_StartMatchingRoomSuccessRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Base_Match3_RoomInfo RoomInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_GetSceneInformationReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_GetSceneInformationRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Ret { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Base_Match3_RoomInfo RoomInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_CountdownRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int TotalNum { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int CountdownNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_StartRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_NextMoveReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string RoleId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int ChairId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Base_Match3_ChessboardInfo ChessboardInfo { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Base_Match3_HeroInfo HeroInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_NextMoveRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Ret { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string RoleId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int ChairId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Base_Match3_ChessboardInfo ChessboardInfo { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public Base_Match3_HeroInfo HeroInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Match3_AttackTargetHero : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string TargetId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int TargetValue { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int TargetHp { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int TargetHpLimit { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_HeroAttackReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string AId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int AValue { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int SkillId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<Base_Match3_AttackTargetHero> AttackTargetHeroList { get; set; } = new global::System.Collections.Generic.List<Base_Match3_AttackTargetHero>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_HeroAttackRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Ret { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string AId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int AValue { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int AHp { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int AHpLimit { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int SkillId { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public global::System.Collections.Generic.List<Base_Match3_AttackTargetHero> AttackTargetHeroList { get; set; } = new global::System.Collections.Generic.List<Base_Match3_AttackTargetHero>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_WaitOtherPlayerOfflineCountdownRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_RoleDeathJieSuanRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Base_Match3_JieSuanRoleInfo JieSuanRoleInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_GameOverRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, Base_Match3_JieSuanRoleInfo> JieSuan { get; set; } = new global::System.Collections.Generic.Dictionary<string, Base_Match3_JieSuanRoleInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_ExitRoomReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_ExitRoomRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Ret { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int RoleId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_OtherRoleExitRoomRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int RoleId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_ReleaseSkillReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int SkillId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int SkillPosition { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_ReleaseSkillRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_EnterRoomReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_EnterRoomRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Ret { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Base_Match3_RoomInfo RoomInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_PrepareReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool IsPrepare { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_PrepareRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int RoleId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool IsPrepare { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_BuyTalentSkillReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int TalentSkillId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_BuyTalentSkillRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Ret { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int TalentSkillId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Match3_NextRoundOperationRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int MaxRoundNum { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int CurrentRoundNum { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string OperationPlayerId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public long OperationPlayerEndTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Match3Game
    {
        GameIdle = 0,
        Game10101 = 10101,
        Game10201 = 10201,
        Game10202 = 10202,
        Game10301 = 10301,
        Game10401 = 10401,
        Game10402 = 10402,
        Game10403 = 10403,
        Game10404 = 10404,
        Game10501 = 10501,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
