// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Net_Backpack.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Pb
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Backpack_BackpackInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> ItemInfoList { get; set; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Backpack_ConsumeOperationOrderInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int OperationType { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int ConsumeItemList { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int AcquireItemList { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Backpack_MoneyInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Coin { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int Gold { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Backpack_AnItemInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int Num { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool IsBind { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string HasParam { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        public long InvalidTime { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int GoldPrice { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Backpack_ItemConsumeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int ConsumeBindItemNum { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int ConsumeNoBindItemNum { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int ConsumeNumList { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Backpack_BuyItemInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int ItemId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int ItemCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Backpack_ItemConsumeList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int BindItemNum { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int NoBindItemNum { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int NeedGoldNum { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int CostBindCoinFirst { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int Count { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsPacked = true)]
        public int[] IndexList { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsPacked = true)]
        public int[] NumList { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int BuyCount { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public global::System.Collections.Generic.List<Base_Backpack_BuyItemInfo> BuyItemInfo { get; set; } = new global::System.Collections.Generic.List<Base_Backpack_BuyItemInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Backpack_GetBackpackInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Backpack_GetBackpackInfoRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Base_Backpack_BackpackInfo BackpackInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Backpack_BackpackUpdateRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int DelItems { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int AddItems { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int UpdateItems { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> UpdateItemList { get; set; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Backpack_UseItemsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int itemId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Backpack_UseItemsRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Ret { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Backpack_CellInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Opened { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int Used { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int Unused { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Backpack_OpenCellReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Backpack_OpenCellRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public enum EBackpack
    {
        EBackpackTypeIdle = 0,
        EBackpackTypeItem = 1,
        EBackpackTypeDepot = 2,
        EBackpackTypeDummy = 3,
        EBackpackMaxGridNum = 100,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EBagId
    {
        EBagIdIdle = 0,
        EBagIdMain = 101,
        EBagIdPet = 102,
        EBagIdDepot = 201,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EItemId
    {
        BackpackItemIdle = 0,
        CoinItemId = 1001,
        GoldItemId = 1002,
        HolyGrailItemId = 2001,
        ItemId4002 = 4002,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EPutReasonType
    {
        PutReasonInvalid = 0,
        PutReasonNoNotice = 1,
        PutReasonGM = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
