// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Net_Player.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Pb
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Player_PlayerData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Base_Player_PlayerInfo PlayerInfo { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public Base_Player_MoneyInfo MoneyInfo { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public Base_Backpack_BackpackInfo BackpackInfo { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public Base_Player_LoginBonusInfo LoginBonusInfo { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public Base_Player_DailyBonusInfo DailyBonusInfo { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public Base_Vip_VipInfo VipInfo { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public Base_Activity_ActivityInfo ActivityInfo { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public Base_Player_ThemeInfo ThemeInfo { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public Base_Shop_ShopInfo ShopInfo { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public Base_Inbox_InboxInfo InboxInfo { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public Base_HeroCard_HeroCardInfo HeroCardInfo { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public Base_Task_TaskInfo TaskInfo { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public Base_Task_CupTaskInfo CupTaskInfo { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public Base_PassCheck_PassCheckInfo PassCheckInfo { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        public Base_Guide_GuideInfo GuideInfo { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        public Base_Match3_Match3Info Match3Info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Player_PlayerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlayerId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string NickName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int Exp { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int ExpLimit { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int Coin { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int Gold { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int HolyGrail { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int IsNewPlayer { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Player_LoginBonusInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int CheckIn { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int TypeWeek { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int WeeklyCount { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int MonthlyCount { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsPacked = true)]
        public int[] MonthStatus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Player_ThemeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Player_DailyBonusInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public int[] DailyBonusStatus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Player_PlayerMark : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int AttributeType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int AttributeValue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Base_Player_MoneyInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Gold { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int GoldBind { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int Coin { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int CoinBind { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int HolyGrail { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int LuckyWheelCoin { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Player_UpdateMoneyInfoRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Base_Player_MoneyInfo MoneyInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Player_PlayerUpdatesInfoRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, Base_Player_PlayerMark> PlayerMarkList { get; set; } = new global::System.Collections.Generic.Dictionary<int, Base_Player_PlayerMark>();

        [global::ProtoBuf.ProtoMember(2)]
        public Base_HeroCard_HeroCardInfo HeroCardInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Base_Activity_ActivityInfo ActivityInfo { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Base_Task_TaskInfo TaskInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Player_ChangeNameReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string NickName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Net_Player_ChangeNameRet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Ret { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string NickName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public enum PlayerMark
    {
        PlayerMarkIdle = 0,
        Coins = 1,
        Golds = 2,
        HolyGrails = 3,
        LoginBonusMark = 9,
        DailyBonusMark = 10,
        StoreMark = 11,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
