// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Proto.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Pb
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlaceHolder3333 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string dec { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public bool flag { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int funID { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsPacked = true)]
        public int[] cards { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AvatarInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int money { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int team_id { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsPacked = true)]
        public int[] cards { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchingSuccess : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, AvatarInfo> AvatarInfos { get; set; } = new global::System.Collections.Generic.Dictionary<int, AvatarInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayedCardInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int team_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int card_value { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int out_card_value { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int cards_left_num { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, AvatarInfo> AvatarInfos { get; set; } = new global::System.Collections.Generic.Dictionary<int, AvatarInfo>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
