// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.1
// source: Net_Ads.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 广告任务
type Base_Ads_AdsTasksInfo struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	AdsTasksItemList []*Base_Ads_AdsTasksItemInfo `protobuf:"bytes,1,rep,name=AdsTasksItemList,proto3" json:"AdsTasksItemList,omitempty"` //广告列表
	AdsBit           int64                        `protobuf:"varint,2,opt,name=AdsBit,proto3" json:"AdsBit,omitempty"`                    //位状态
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Base_Ads_AdsTasksInfo) Reset() {
	*x = Base_Ads_AdsTasksInfo{}
	mi := &file_Net_Ads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base_Ads_AdsTasksInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base_Ads_AdsTasksInfo) ProtoMessage() {}

func (x *Base_Ads_AdsTasksInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Ads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base_Ads_AdsTasksInfo.ProtoReflect.Descriptor instead.
func (*Base_Ads_AdsTasksInfo) Descriptor() ([]byte, []int) {
	return file_Net_Ads_proto_rawDescGZIP(), []int{0}
}

func (x *Base_Ads_AdsTasksInfo) GetAdsTasksItemList() []*Base_Ads_AdsTasksItemInfo {
	if x != nil {
		return x.AdsTasksItemList
	}
	return nil
}

func (x *Base_Ads_AdsTasksInfo) GetAdsBit() int64 {
	if x != nil {
		return x.AdsBit
	}
	return 0
}

// 广告任务item
type Base_Ads_AdsTasksItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`           //广告Id
	ItemId        int32                  `protobuf:"varint,2,opt,name=ItemId,proto3" json:"ItemId,omitempty"`   //物品Id
	ItemNum       int32                  `protobuf:"varint,3,opt,name=ItemNum,proto3" json:"ItemNum,omitempty"` //数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base_Ads_AdsTasksItemInfo) Reset() {
	*x = Base_Ads_AdsTasksItemInfo{}
	mi := &file_Net_Ads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base_Ads_AdsTasksItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base_Ads_AdsTasksItemInfo) ProtoMessage() {}

func (x *Base_Ads_AdsTasksItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Ads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base_Ads_AdsTasksItemInfo.ProtoReflect.Descriptor instead.
func (*Base_Ads_AdsTasksItemInfo) Descriptor() ([]byte, []int) {
	return file_Net_Ads_proto_rawDescGZIP(), []int{1}
}

func (x *Base_Ads_AdsTasksItemInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Base_Ads_AdsTasksItemInfo) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Base_Ads_AdsTasksItemInfo) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

// 收集广告奖励
type Net_Ads_CollectAdsRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=TaskId,proto3" json:"TaskId,omitempty"` //任务Id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Net_Ads_CollectAdsRewardReq) Reset() {
	*x = Net_Ads_CollectAdsRewardReq{}
	mi := &file_Net_Ads_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Net_Ads_CollectAdsRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Ads_CollectAdsRewardReq) ProtoMessage() {}

func (x *Net_Ads_CollectAdsRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Ads_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Ads_CollectAdsRewardReq.ProtoReflect.Descriptor instead.
func (*Net_Ads_CollectAdsRewardReq) Descriptor() ([]byte, []int) {
	return file_Net_Ads_proto_rawDescGZIP(), []int{2}
}

func (x *Net_Ads_CollectAdsRewardReq) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type Net_Ads_CollectAdsRewardRet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           int32                  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"` //0:领取成功;1:未知错误;2:已经领取;3:条件不满足;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Net_Ads_CollectAdsRewardRet) Reset() {
	*x = Net_Ads_CollectAdsRewardRet{}
	mi := &file_Net_Ads_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Net_Ads_CollectAdsRewardRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Ads_CollectAdsRewardRet) ProtoMessage() {}

func (x *Net_Ads_CollectAdsRewardRet) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Ads_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Ads_CollectAdsRewardRet.ProtoReflect.Descriptor instead.
func (*Net_Ads_CollectAdsRewardRet) Descriptor() ([]byte, []int) {
	return file_Net_Ads_proto_rawDescGZIP(), []int{3}
}

func (x *Net_Ads_CollectAdsRewardRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

var File_Net_Ads_proto protoreflect.FileDescriptor

const file_Net_Ads_proto_rawDesc = "" +
	"\n" +
	"\rNet_Ads.proto\x12\x02Pb\"z\n" +
	"\x15Base_Ads_AdsTasksInfo\x12I\n" +
	"\x10AdsTasksItemList\x18\x01 \x03(\v2\x1d.Pb.Base_Ads_AdsTasksItemInfoR\x10AdsTasksItemList\x12\x16\n" +
	"\x06AdsBit\x18\x02 \x01(\x03R\x06AdsBit\"]\n" +
	"\x19Base_Ads_AdsTasksItemInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06ItemId\x18\x02 \x01(\x05R\x06ItemId\x12\x18\n" +
	"\aItemNum\x18\x03 \x01(\x05R\aItemNum\"5\n" +
	"\x1bNet_Ads_CollectAdsRewardReq\x12\x16\n" +
	"\x06TaskId\x18\x01 \x01(\x05R\x06TaskId\"/\n" +
	"\x1bNet_Ads_CollectAdsRewardRet\x12\x10\n" +
	"\x03Ret\x18\x01 \x01(\x05R\x03RetB\x06Z\x04./pbb\x06proto3"

var (
	file_Net_Ads_proto_rawDescOnce sync.Once
	file_Net_Ads_proto_rawDescData []byte
)

func file_Net_Ads_proto_rawDescGZIP() []byte {
	file_Net_Ads_proto_rawDescOnce.Do(func() {
		file_Net_Ads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Net_Ads_proto_rawDesc), len(file_Net_Ads_proto_rawDesc)))
	})
	return file_Net_Ads_proto_rawDescData
}

var file_Net_Ads_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Net_Ads_proto_goTypes = []any{
	(*Base_Ads_AdsTasksInfo)(nil),       // 0: Pb.Base_Ads_AdsTasksInfo
	(*Base_Ads_AdsTasksItemInfo)(nil),   // 1: Pb.Base_Ads_AdsTasksItemInfo
	(*Net_Ads_CollectAdsRewardReq)(nil), // 2: Pb.Net_Ads_CollectAdsRewardReq
	(*Net_Ads_CollectAdsRewardRet)(nil), // 3: Pb.Net_Ads_CollectAdsRewardRet
}
var file_Net_Ads_proto_depIdxs = []int32{
	1, // 0: Pb.Base_Ads_AdsTasksInfo.AdsTasksItemList:type_name -> Pb.Base_Ads_AdsTasksItemInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Net_Ads_proto_init() }
func file_Net_Ads_proto_init() {
	if File_Net_Ads_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Net_Ads_proto_rawDesc), len(file_Net_Ads_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Net_Ads_proto_goTypes,
		DependencyIndexes: file_Net_Ads_proto_depIdxs,
		MessageInfos:      file_Net_Ads_proto_msgTypes,
	}.Build()
	File_Net_Ads_proto = out.File
	file_Net_Ads_proto_goTypes = nil
	file_Net_Ads_proto_depIdxs = nil
}
