// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.23.1
// source: Net_Shop.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商店一个物品
type Base_Shop_AnItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`         //物品Id
	BuyNum int32 `protobuf:"varint,2,opt,name=BuyNum,proto3" json:"BuyNum,omitempty"` //已经购买数量
}

func (x *Base_Shop_AnItemInfo) Reset() {
	*x = Base_Shop_AnItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Shop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Base_Shop_AnItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base_Shop_AnItemInfo) ProtoMessage() {}

func (x *Base_Shop_AnItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Shop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base_Shop_AnItemInfo.ProtoReflect.Descriptor instead.
func (*Base_Shop_AnItemInfo) Descriptor() ([]byte, []int) {
	return file_Net_Shop_proto_rawDescGZIP(), []int{0}
}

func (x *Base_Shop_AnItemInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Base_Shop_AnItemInfo) GetBuyNum() int32 {
	if x != nil {
		return x.BuyNum
	}
	return 0
}

// 一个货架
type Base_Shop_ShelvesInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32                   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                           //货架Id
	Name            string                  `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`                        //货架名字
	Quantity        int32                   `protobuf:"varint,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`               //展示数量
	ItemList        []*Base_Shop_AnItemInfo `protobuf:"bytes,4,rep,name=ItemList,proto3" json:"ItemList,omitempty"`                //货架物品
	NextRefreshTime int64                   `protobuf:"varint,5,opt,name=NextRefreshTime,proto3" json:"NextRefreshTime,omitempty"` //下次刷新时间
}

func (x *Base_Shop_ShelvesInfo) Reset() {
	*x = Base_Shop_ShelvesInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Shop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Base_Shop_ShelvesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base_Shop_ShelvesInfo) ProtoMessage() {}

func (x *Base_Shop_ShelvesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Shop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base_Shop_ShelvesInfo.ProtoReflect.Descriptor instead.
func (*Base_Shop_ShelvesInfo) Descriptor() ([]byte, []int) {
	return file_Net_Shop_proto_rawDescGZIP(), []int{1}
}

func (x *Base_Shop_ShelvesInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Base_Shop_ShelvesInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Base_Shop_ShelvesInfo) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Base_Shop_ShelvesInfo) GetItemList() []*Base_Shop_AnItemInfo {
	if x != nil {
		return x.ItemList
	}
	return nil
}

func (x *Base_Shop_ShelvesInfo) GetNextRefreshTime() int64 {
	if x != nil {
		return x.NextRefreshTime
	}
	return 0
}

// 一个商店信息
type Base_Shop_AShopInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32                    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`            //商店Id
	Name     string                   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`         //商店名字
	ItemList []*Base_Shop_ShelvesInfo `protobuf:"bytes,5,rep,name=ItemList,proto3" json:"ItemList,omitempty"` //货架数组
}

func (x *Base_Shop_AShopInfo) Reset() {
	*x = Base_Shop_AShopInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Shop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Base_Shop_AShopInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base_Shop_AShopInfo) ProtoMessage() {}

func (x *Base_Shop_AShopInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Shop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base_Shop_AShopInfo.ProtoReflect.Descriptor instead.
func (*Base_Shop_AShopInfo) Descriptor() ([]byte, []int) {
	return file_Net_Shop_proto_rawDescGZIP(), []int{2}
}

func (x *Base_Shop_AShopInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Base_Shop_AShopInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Base_Shop_AShopInfo) GetItemList() []*Base_Shop_ShelvesInfo {
	if x != nil {
		return x.ItemList
	}
	return nil
}

// 商店信息
type Base_Shop_ShopInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AShopInfoList       []*Base_Shop_AShopInfo          `protobuf:"bytes,1,rep,name=AShopInfoList,proto3" json:"AShopInfoList,omitempty"`                                                                                                      //商店列表信息
	ShopBuyLimitNumList map[int32]*Base_Shop_AnItemInfo `protobuf:"bytes,2,rep,name=ShopBuyLimitNumList,proto3" json:"ShopBuyLimitNumList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //玩家已经购买列表
}

func (x *Base_Shop_ShopInfo) Reset() {
	*x = Base_Shop_ShopInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Shop_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Base_Shop_ShopInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base_Shop_ShopInfo) ProtoMessage() {}

func (x *Base_Shop_ShopInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Shop_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base_Shop_ShopInfo.ProtoReflect.Descriptor instead.
func (*Base_Shop_ShopInfo) Descriptor() ([]byte, []int) {
	return file_Net_Shop_proto_rawDescGZIP(), []int{3}
}

func (x *Base_Shop_ShopInfo) GetAShopInfoList() []*Base_Shop_AShopInfo {
	if x != nil {
		return x.AShopInfoList
	}
	return nil
}

func (x *Base_Shop_ShopInfo) GetShopBuyLimitNumList() map[int32]*Base_Shop_AnItemInfo {
	if x != nil {
		return x.ShopBuyLimitNumList
	}
	return nil
}

// ------消息------------------------------------------------
// 获取获取商店信息
type Net_Shop_GetShopInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Net_Shop_GetShopInfoReq) Reset() {
	*x = Net_Shop_GetShopInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Shop_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Shop_GetShopInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Shop_GetShopInfoReq) ProtoMessage() {}

func (x *Net_Shop_GetShopInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Shop_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Shop_GetShopInfoReq.ProtoReflect.Descriptor instead.
func (*Net_Shop_GetShopInfoReq) Descriptor() ([]byte, []int) {
	return file_Net_Shop_proto_rawDescGZIP(), []int{4}
}

// 获取获取商店信息
type Net_Shop_GetShopInfoRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopInfo *Base_Shop_ShopInfo `protobuf:"bytes,1,opt,name=ShopInfo,proto3" json:"ShopInfo,omitempty"` //商店信息
}

func (x *Net_Shop_GetShopInfoRet) Reset() {
	*x = Net_Shop_GetShopInfoRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Shop_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Shop_GetShopInfoRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Shop_GetShopInfoRet) ProtoMessage() {}

func (x *Net_Shop_GetShopInfoRet) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Shop_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Shop_GetShopInfoRet.ProtoReflect.Descriptor instead.
func (*Net_Shop_GetShopInfoRet) Descriptor() ([]byte, []int) {
	return file_Net_Shop_proto_rawDescGZIP(), []int{5}
}

func (x *Net_Shop_GetShopInfoRet) GetShopInfo() *Base_Shop_ShopInfo {
	if x != nil {
		return x.ShopInfo
	}
	return nil
}

// 购买商品
type Net_Shop_BuyItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopItemId  int32 `protobuf:"varint,1,opt,name=ShopItemId,proto3" json:"ShopItemId,omitempty"`   //购买商品Id
	ShopItemNum int32 `protobuf:"varint,2,opt,name=ShopItemNum,proto3" json:"ShopItemNum,omitempty"` //购买商品数量
}

func (x *Net_Shop_BuyItemReq) Reset() {
	*x = Net_Shop_BuyItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Shop_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Shop_BuyItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Shop_BuyItemReq) ProtoMessage() {}

func (x *Net_Shop_BuyItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Shop_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Shop_BuyItemReq.ProtoReflect.Descriptor instead.
func (*Net_Shop_BuyItemReq) Descriptor() ([]byte, []int) {
	return file_Net_Shop_proto_rawDescGZIP(), []int{6}
}

func (x *Net_Shop_BuyItemReq) GetShopItemId() int32 {
	if x != nil {
		return x.ShopItemId
	}
	return 0
}

func (x *Net_Shop_BuyItemReq) GetShopItemNum() int32 {
	if x != nil {
		return x.ShopItemNum
	}
	return 0
}

type Net_Shop_BuyItemRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret         int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`                 //0:成功;1:未知错误;2:数量不能小于0;3:购买上限;4:条件未满足;
	ShopItemId  int32 `protobuf:"varint,2,opt,name=ShopItemId,proto3" json:"ShopItemId,omitempty"`   //购买商品Id
	ShopItemNum int32 `protobuf:"varint,3,opt,name=ShopItemNum,proto3" json:"ShopItemNum,omitempty"` //购买商品数量
	ItemId      int32 `protobuf:"varint,4,opt,name=ItemId,proto3" json:"ItemId,omitempty"`           //购买物品Id
	ItemNum     int32 `protobuf:"varint,5,opt,name=ItemNum,proto3" json:"ItemNum,omitempty"`         //购买物品数量
}

func (x *Net_Shop_BuyItemRet) Reset() {
	*x = Net_Shop_BuyItemRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Shop_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Shop_BuyItemRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Shop_BuyItemRet) ProtoMessage() {}

func (x *Net_Shop_BuyItemRet) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Shop_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Shop_BuyItemRet.ProtoReflect.Descriptor instead.
func (*Net_Shop_BuyItemRet) Descriptor() ([]byte, []int) {
	return file_Net_Shop_proto_rawDescGZIP(), []int{7}
}

func (x *Net_Shop_BuyItemRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *Net_Shop_BuyItemRet) GetShopItemId() int32 {
	if x != nil {
		return x.ShopItemId
	}
	return 0
}

func (x *Net_Shop_BuyItemRet) GetShopItemNum() int32 {
	if x != nil {
		return x.ShopItemNum
	}
	return 0
}

func (x *Net_Shop_BuyItemRet) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Net_Shop_BuyItemRet) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

// 支付:->购买商品回来转发服务器
type Net_Shop_PayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd         int32  `protobuf:"varint,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"` //1:CmdGoogleVerify;2:CmdIosVerify;
	Data        string `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	ShopItemId  int32  `protobuf:"varint,3,opt,name=ShopItemId,proto3" json:"ShopItemId,omitempty"`   //购买商品Id
	ShopItemNum int32  `protobuf:"varint,4,opt,name=ShopItemNum,proto3" json:"ShopItemNum,omitempty"` //购买商品数量
}

func (x *Net_Shop_PayReq) Reset() {
	*x = Net_Shop_PayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Shop_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Shop_PayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Shop_PayReq) ProtoMessage() {}

func (x *Net_Shop_PayReq) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Shop_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Shop_PayReq.ProtoReflect.Descriptor instead.
func (*Net_Shop_PayReq) Descriptor() ([]byte, []int) {
	return file_Net_Shop_proto_rawDescGZIP(), []int{8}
}

func (x *Net_Shop_PayReq) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *Net_Shop_PayReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Net_Shop_PayReq) GetShopItemId() int32 {
	if x != nil {
		return x.ShopItemId
	}
	return 0
}

func (x *Net_Shop_PayReq) GetShopItemNum() int32 {
	if x != nil {
		return x.ShopItemNum
	}
	return 0
}

type Net_Shop_PayRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`             //
	ProductId int32  `protobuf:"varint,2,opt,name=ProductId,proto3" json:"ProductId,omitempty"` //购买商品数量
	OrderId   string `protobuf:"bytes,3,opt,name=OrderId,proto3" json:"OrderId,omitempty"`      //订单Id
	Price     int32  `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`         //价格
	Status    int32  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`       //
}

func (x *Net_Shop_PayRet) Reset() {
	*x = Net_Shop_PayRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Shop_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Shop_PayRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Shop_PayRet) ProtoMessage() {}

func (x *Net_Shop_PayRet) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Shop_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Shop_PayRet.ProtoReflect.Descriptor instead.
func (*Net_Shop_PayRet) Descriptor() ([]byte, []int) {
	return file_Net_Shop_proto_rawDescGZIP(), []int{9}
}

func (x *Net_Shop_PayRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *Net_Shop_PayRet) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Net_Shop_PayRet) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Net_Shop_PayRet) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Net_Shop_PayRet) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_Net_Shop_proto protoreflect.FileDescriptor

var file_Net_Shop_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x4e, 0x65, 0x74, 0x5f, 0x53, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x50, 0x62, 0x22, 0x3e, 0x0a, 0x14, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x53, 0x68, 0x6f,
	0x70, 0x5f, 0x41, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x42, 0x75, 0x79, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x42, 0x75,
	0x79, 0x4e, 0x75, 0x6d, 0x22, 0xb7, 0x01, 0x0a, 0x15, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x53, 0x68,
	0x6f, 0x70, 0x5f, 0x53, 0x68, 0x65, 0x6c, 0x76, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x34,
	0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x50, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x53, 0x68, 0x6f, 0x70, 0x5f,
	0x41, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x49, 0x74, 0x65, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x4e,
	0x65, 0x78, 0x74, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x70,
	0x0a, 0x13, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x53, 0x68, 0x6f, 0x70, 0x5f, 0x41, 0x53, 0x68, 0x6f,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x49, 0x74, 0x65,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x50, 0x62,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x53, 0x68, 0x6f, 0x70, 0x5f, 0x53, 0x68, 0x65, 0x6c, 0x76,
	0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x98, 0x02, 0x0a, 0x12, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x53, 0x68, 0x6f, 0x70, 0x5f, 0x53,
	0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x0d, 0x41, 0x53, 0x68, 0x6f, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x50, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x53, 0x68, 0x6f, 0x70, 0x5f, 0x41, 0x53,
	0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x41, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x61, 0x0a, 0x13, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x75,
	0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4e, 0x75, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x50, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x53, 0x68,
	0x6f, 0x70, 0x5f, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70,
	0x42, 0x75, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4e, 0x75, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x13, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x75, 0x79, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x4e, 0x75, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x60, 0x0a, 0x18, 0x53, 0x68, 0x6f,
	0x70, 0x42, 0x75, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4e, 0x75, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x50, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x5f, 0x53, 0x68, 0x6f, 0x70, 0x5f, 0x41, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x19, 0x0a, 0x17, 0x4e,
	0x65, 0x74, 0x5f, 0x53, 0x68, 0x6f, 0x70, 0x5f, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x4d, 0x0a, 0x17, 0x4e, 0x65, 0x74, 0x5f, 0x53, 0x68,
	0x6f, 0x70, 0x5f, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x74, 0x12, 0x32, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x50, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x53, 0x68,
	0x6f, 0x70, 0x5f, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x53, 0x68, 0x6f,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x57, 0x0a, 0x13, 0x4e, 0x65, 0x74, 0x5f, 0x53, 0x68, 0x6f,
	0x70, 0x5f, 0x42, 0x75, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a,
	0x53, 0x68, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x53, 0x68, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x22, 0x9b,
	0x01, 0x0a, 0x13, 0x4e, 0x65, 0x74, 0x5f, 0x53, 0x68, 0x6f, 0x70, 0x5f, 0x42, 0x75, 0x79, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x70,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x68,
	0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x70,
	0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x53,
	0x68, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x22, 0x79, 0x0a, 0x0f,
	0x4e, 0x65, 0x74, 0x5f, 0x53, 0x68, 0x6f, 0x70, 0x5f, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x43, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x43, 0x6d,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x68, 0x6f, 0x70, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x74, 0x65,
	0x6d, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x53, 0x68, 0x6f, 0x70,
	0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x22, 0x89, 0x01, 0x0a, 0x0f, 0x4e, 0x65, 0x74, 0x5f,
	0x53, 0x68, 0x6f, 0x70, 0x5f, 0x50, 0x61, 0x79, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x52,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_Net_Shop_proto_rawDescOnce sync.Once
	file_Net_Shop_proto_rawDescData = file_Net_Shop_proto_rawDesc
)

func file_Net_Shop_proto_rawDescGZIP() []byte {
	file_Net_Shop_proto_rawDescOnce.Do(func() {
		file_Net_Shop_proto_rawDescData = protoimpl.X.CompressGZIP(file_Net_Shop_proto_rawDescData)
	})
	return file_Net_Shop_proto_rawDescData
}

var file_Net_Shop_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_Net_Shop_proto_goTypes = []interface{}{
	(*Base_Shop_AnItemInfo)(nil),    // 0: Pb.Base_Shop_AnItemInfo
	(*Base_Shop_ShelvesInfo)(nil),   // 1: Pb.Base_Shop_ShelvesInfo
	(*Base_Shop_AShopInfo)(nil),     // 2: Pb.Base_Shop_AShopInfo
	(*Base_Shop_ShopInfo)(nil),      // 3: Pb.Base_Shop_ShopInfo
	(*Net_Shop_GetShopInfoReq)(nil), // 4: Pb.Net_Shop_GetShopInfoReq
	(*Net_Shop_GetShopInfoRet)(nil), // 5: Pb.Net_Shop_GetShopInfoRet
	(*Net_Shop_BuyItemReq)(nil),     // 6: Pb.Net_Shop_BuyItemReq
	(*Net_Shop_BuyItemRet)(nil),     // 7: Pb.Net_Shop_BuyItemRet
	(*Net_Shop_PayReq)(nil),         // 8: Pb.Net_Shop_PayReq
	(*Net_Shop_PayRet)(nil),         // 9: Pb.Net_Shop_PayRet
	nil,                             // 10: Pb.Base_Shop_ShopInfo.ShopBuyLimitNumListEntry
}
var file_Net_Shop_proto_depIdxs = []int32{
	0,  // 0: Pb.Base_Shop_ShelvesInfo.ItemList:type_name -> Pb.Base_Shop_AnItemInfo
	1,  // 1: Pb.Base_Shop_AShopInfo.ItemList:type_name -> Pb.Base_Shop_ShelvesInfo
	2,  // 2: Pb.Base_Shop_ShopInfo.AShopInfoList:type_name -> Pb.Base_Shop_AShopInfo
	10, // 3: Pb.Base_Shop_ShopInfo.ShopBuyLimitNumList:type_name -> Pb.Base_Shop_ShopInfo.ShopBuyLimitNumListEntry
	3,  // 4: Pb.Net_Shop_GetShopInfoRet.ShopInfo:type_name -> Pb.Base_Shop_ShopInfo
	0,  // 5: Pb.Base_Shop_ShopInfo.ShopBuyLimitNumListEntry.value:type_name -> Pb.Base_Shop_AnItemInfo
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_Net_Shop_proto_init() }
func file_Net_Shop_proto_init() {
	if File_Net_Shop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Net_Shop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Base_Shop_AnItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Shop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Base_Shop_ShelvesInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Shop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Base_Shop_AShopInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Shop_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Base_Shop_ShopInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Shop_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Shop_GetShopInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Shop_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Shop_GetShopInfoRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Shop_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Shop_BuyItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Shop_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Shop_BuyItemRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Shop_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Shop_PayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Shop_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Shop_PayRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Net_Shop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Net_Shop_proto_goTypes,
		DependencyIndexes: file_Net_Shop_proto_depIdxs,
		MessageInfos:      file_Net_Shop_proto_msgTypes,
	}.Build()
	File_Net_Shop_proto = out.File
	file_Net_Shop_proto_rawDesc = nil
	file_Net_Shop_proto_goTypes = nil
	file_Net_Shop_proto_depIdxs = nil
}
