// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.23.1
// source: Net_Error.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码
//
// added by yh @ 2024/03/16 14:55
// 注意:服务器主动发送客户端提示的错误码
type EErrorNum int32

const (
	EErrorNum_ErrorNumIde                EErrorNum = 0
	EErrorNum_EN_KNAPSACK_USE_NOT_DIRECT EErrorNum = 1
)

// Enum value maps for EErrorNum.
var (
	EErrorNum_name = map[int32]string{
		0: "ErrorNumIde",
		1: "EN_KNAPSACK_USE_NOT_DIRECT",
	}
	EErrorNum_value = map[string]int32{
		"ErrorNumIde":                0,
		"EN_KNAPSACK_USE_NOT_DIRECT": 1,
	}
)

func (x EErrorNum) Enum() *EErrorNum {
	p := new(EErrorNum)
	*p = x
	return p
}

func (x EErrorNum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EErrorNum) Descriptor() protoreflect.EnumDescriptor {
	return file_Net_Error_proto_enumTypes[0].Descriptor()
}

func (EErrorNum) Type() protoreflect.EnumType {
	return &file_Net_Error_proto_enumTypes[0]
}

func (x EErrorNum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EErrorNum.Descriptor instead.
func (EErrorNum) EnumDescriptor() ([]byte, []int) {
	return file_Net_Error_proto_rawDescGZIP(), []int{0}
}

// 服务器主推通用错误提示
type Net_Error_ErrorRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"` //错误码
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`    //
}

func (x *Net_Error_ErrorRet) Reset() {
	*x = Net_Error_ErrorRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Error_ErrorRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Error_ErrorRet) ProtoMessage() {}

func (x *Net_Error_ErrorRet) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Error_ErrorRet.ProtoReflect.Descriptor instead.
func (*Net_Error_ErrorRet) Descriptor() ([]byte, []int) {
	return file_Net_Error_proto_rawDescGZIP(), []int{0}
}

func (x *Net_Error_ErrorRet) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Net_Error_ErrorRet) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_Net_Error_proto protoreflect.FileDescriptor

var file_Net_Error_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x4e, 0x65, 0x74, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x50, 0x62, 0x22, 0x3a, 0x0a, 0x12, 0x4e, 0x65, 0x74, 0x5f, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73,
	0x67, 0x2a, 0x3c, 0x0a, 0x09, 0x45, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x0f,
	0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x49, 0x64, 0x65, 0x10, 0x00, 0x12,
	0x1e, 0x0a, 0x1a, 0x45, 0x4e, 0x5f, 0x4b, 0x4e, 0x41, 0x50, 0x53, 0x41, 0x43, 0x4b, 0x5f, 0x55,
	0x53, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x10, 0x01, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Net_Error_proto_rawDescOnce sync.Once
	file_Net_Error_proto_rawDescData = file_Net_Error_proto_rawDesc
)

func file_Net_Error_proto_rawDescGZIP() []byte {
	file_Net_Error_proto_rawDescOnce.Do(func() {
		file_Net_Error_proto_rawDescData = protoimpl.X.CompressGZIP(file_Net_Error_proto_rawDescData)
	})
	return file_Net_Error_proto_rawDescData
}

var file_Net_Error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Net_Error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Net_Error_proto_goTypes = []interface{}{
	(EErrorNum)(0),             // 0: Pb.EErrorNum
	(*Net_Error_ErrorRet)(nil), // 1: Pb.Net_Error_ErrorRet
}
var file_Net_Error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Net_Error_proto_init() }
func file_Net_Error_proto_init() {
	if File_Net_Error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Net_Error_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Error_ErrorRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Net_Error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Net_Error_proto_goTypes,
		DependencyIndexes: file_Net_Error_proto_depIdxs,
		EnumInfos:         file_Net_Error_proto_enumTypes,
		MessageInfos:      file_Net_Error_proto_msgTypes,
	}.Build()
	File_Net_Error_proto = out.File
	file_Net_Error_proto_rawDesc = nil
	file_Net_Error_proto_goTypes = nil
	file_Net_Error_proto_depIdxs = nil
}
