// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.23.1
// source: Net_Inbox.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息模块
type InboxType int32

const (
	InboxType_InboxIdle    InboxType = 0
	InboxType_InboxTypeSys InboxType = 1 //系统
)

// Enum value maps for InboxType.
var (
	InboxType_name = map[int32]string{
		0: "InboxIdle",
		1: "InboxTypeSys",
	}
	InboxType_value = map[string]int32{
		"InboxIdle":    0,
		"InboxTypeSys": 1,
	}
)

func (x InboxType) Enum() *InboxType {
	p := new(InboxType)
	*p = x
	return p
}

func (x InboxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InboxType) Descriptor() protoreflect.EnumDescriptor {
	return file_Net_Inbox_proto_enumTypes[0].Descriptor()
}

func (InboxType) Type() protoreflect.EnumType {
	return &file_Net_Inbox_proto_enumTypes[0]
}

func (x InboxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InboxType.Descriptor instead.
func (InboxType) EnumDescriptor() ([]byte, []int) {
	return file_Net_Inbox_proto_rawDescGZIP(), []int{0}
}

// 收件箱信息
type Base_Inbox_InboxInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemList []*Base_Inbox_InboxItemInfo `protobuf:"bytes,1,rep,name=ItemList,proto3" json:"ItemList,omitempty"` //邮件信息列表
}

func (x *Base_Inbox_InboxInfo) Reset() {
	*x = Base_Inbox_InboxInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Inbox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Base_Inbox_InboxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base_Inbox_InboxInfo) ProtoMessage() {}

func (x *Base_Inbox_InboxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Inbox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base_Inbox_InboxInfo.ProtoReflect.Descriptor instead.
func (*Base_Inbox_InboxInfo) Descriptor() ([]byte, []int) {
	return file_Net_Inbox_proto_rawDescGZIP(), []int{0}
}

func (x *Base_Inbox_InboxInfo) GetItemList() []*Base_Inbox_InboxItemInfo {
	if x != nil {
		return x.ItemList
	}
	return nil
}

// 一封邮件
type Base_Inbox_InboxItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                       //邮件Id
	Type          int32  `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`                   //类型
	ReceiverId    string `protobuf:"bytes,3,opt,name=ReceiverId,proto3" json:"ReceiverId,omitempty"`        //收件人
	SenderId      string `protobuf:"bytes,4,opt,name=SenderId,proto3" json:"SenderId,omitempty"`            //发件人
	SenderName    string `protobuf:"bytes,5,opt,name=SenderName,proto3" json:"SenderName,omitempty"`        //发件人名字
	Title         string `protobuf:"bytes,6,opt,name=Title,proto3" json:"Title,omitempty"`                  //邮件标题
	Content       string `protobuf:"bytes,7,opt,name=Content,proto3" json:"Content,omitempty"`              //内容
	IsRead        bool   `protobuf:"varint,8,opt,name=IsRead,proto3" json:"IsRead,omitempty"`               //是否读取 false:未读;true:读取;
	IsClaimReward bool   `protobuf:"varint,9,opt,name=IsClaimReward,proto3" json:"IsClaimReward,omitempty"` //是否领取奖励 false:未领取;true:领取;
	ItemId1       int32  `protobuf:"varint,10,opt,name=ItemId1,proto3" json:"ItemId1,omitempty"`            //物品Id
	ItemNum1      int32  `protobuf:"varint,11,opt,name=ItemNum1,proto3" json:"ItemNum1,omitempty"`          //物品数量
	ItemId2       int32  `protobuf:"varint,12,opt,name=ItemId2,proto3" json:"ItemId2,omitempty"`            //物品Id
	ItemNum2      int32  `protobuf:"varint,13,opt,name=ItemNum2,proto3" json:"ItemNum2,omitempty"`          //物品数量
	ItemId3       int32  `protobuf:"varint,14,opt,name=ItemId3,proto3" json:"ItemId3,omitempty"`            //物品Id
	ItemNum3      int32  `protobuf:"varint,15,opt,name=ItemNum3,proto3" json:"ItemNum3,omitempty"`          //物品数量
	Ts            int64  `protobuf:"varint,16,opt,name=Ts,proto3" json:"Ts,omitempty"`                      //创建时间
}

func (x *Base_Inbox_InboxItemInfo) Reset() {
	*x = Base_Inbox_InboxItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Inbox_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Base_Inbox_InboxItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base_Inbox_InboxItemInfo) ProtoMessage() {}

func (x *Base_Inbox_InboxItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Inbox_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base_Inbox_InboxItemInfo.ProtoReflect.Descriptor instead.
func (*Base_Inbox_InboxItemInfo) Descriptor() ([]byte, []int) {
	return file_Net_Inbox_proto_rawDescGZIP(), []int{1}
}

func (x *Base_Inbox_InboxItemInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Base_Inbox_InboxItemInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Base_Inbox_InboxItemInfo) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Base_Inbox_InboxItemInfo) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Base_Inbox_InboxItemInfo) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Base_Inbox_InboxItemInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Base_Inbox_InboxItemInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Base_Inbox_InboxItemInfo) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Base_Inbox_InboxItemInfo) GetIsClaimReward() bool {
	if x != nil {
		return x.IsClaimReward
	}
	return false
}

func (x *Base_Inbox_InboxItemInfo) GetItemId1() int32 {
	if x != nil {
		return x.ItemId1
	}
	return 0
}

func (x *Base_Inbox_InboxItemInfo) GetItemNum1() int32 {
	if x != nil {
		return x.ItemNum1
	}
	return 0
}

func (x *Base_Inbox_InboxItemInfo) GetItemId2() int32 {
	if x != nil {
		return x.ItemId2
	}
	return 0
}

func (x *Base_Inbox_InboxItemInfo) GetItemNum2() int32 {
	if x != nil {
		return x.ItemNum2
	}
	return 0
}

func (x *Base_Inbox_InboxItemInfo) GetItemId3() int32 {
	if x != nil {
		return x.ItemId3
	}
	return 0
}

func (x *Base_Inbox_InboxItemInfo) GetItemNum3() int32 {
	if x != nil {
		return x.ItemNum3
	}
	return 0
}

func (x *Base_Inbox_InboxItemInfo) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

// -------------------------------------------------
// 主动更新
type Net_Inbox_UpdateItemsInfoRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateItemList map[int32]*Base_Inbox_InboxItemInfo `protobuf:"bytes,1,rep,name=UpdateItemList,proto3" json:"UpdateItemList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //
}

func (x *Net_Inbox_UpdateItemsInfoRet) Reset() {
	*x = Net_Inbox_UpdateItemsInfoRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Inbox_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Inbox_UpdateItemsInfoRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Inbox_UpdateItemsInfoRet) ProtoMessage() {}

func (x *Net_Inbox_UpdateItemsInfoRet) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Inbox_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Inbox_UpdateItemsInfoRet.ProtoReflect.Descriptor instead.
func (*Net_Inbox_UpdateItemsInfoRet) Descriptor() ([]byte, []int) {
	return file_Net_Inbox_proto_rawDescGZIP(), []int{2}
}

func (x *Net_Inbox_UpdateItemsInfoRet) GetUpdateItemList() map[int32]*Base_Inbox_InboxItemInfo {
	if x != nil {
		return x.UpdateItemList
	}
	return nil
}

// 发送邮件
type Net_Inbox_SendEmailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InboxItemInfo *Base_Inbox_InboxItemInfo `protobuf:"bytes,1,opt,name=InboxItemInfo,proto3" json:"InboxItemInfo,omitempty"` //一封邮件
}

func (x *Net_Inbox_SendEmailReq) Reset() {
	*x = Net_Inbox_SendEmailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Inbox_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Inbox_SendEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Inbox_SendEmailReq) ProtoMessage() {}

func (x *Net_Inbox_SendEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Inbox_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Inbox_SendEmailReq.ProtoReflect.Descriptor instead.
func (*Net_Inbox_SendEmailReq) Descriptor() ([]byte, []int) {
	return file_Net_Inbox_proto_rawDescGZIP(), []int{3}
}

func (x *Net_Inbox_SendEmailReq) GetInboxItemInfo() *Base_Inbox_InboxItemInfo {
	if x != nil {
		return x.InboxItemInfo
	}
	return nil
}

type Net_Inbox_SendEmailRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"` //0:成功;1:未知错误;
}

func (x *Net_Inbox_SendEmailRet) Reset() {
	*x = Net_Inbox_SendEmailRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Inbox_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Inbox_SendEmailRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Inbox_SendEmailRet) ProtoMessage() {}

func (x *Net_Inbox_SendEmailRet) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Inbox_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Inbox_SendEmailRet.ProtoReflect.Descriptor instead.
func (*Net_Inbox_SendEmailRet) Descriptor() ([]byte, []int) {
	return file_Net_Inbox_proto_rawDescGZIP(), []int{4}
}

func (x *Net_Inbox_SendEmailRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

// 删除邮件
type Net_Inbox_DeleteEmailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailIds []int32 `protobuf:"varint,1,rep,packed,name=EmailIds,proto3" json:"EmailIds,omitempty"` //邮件Id数组
}

func (x *Net_Inbox_DeleteEmailReq) Reset() {
	*x = Net_Inbox_DeleteEmailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Inbox_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Inbox_DeleteEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Inbox_DeleteEmailReq) ProtoMessage() {}

func (x *Net_Inbox_DeleteEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Inbox_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Inbox_DeleteEmailReq.ProtoReflect.Descriptor instead.
func (*Net_Inbox_DeleteEmailReq) Descriptor() ([]byte, []int) {
	return file_Net_Inbox_proto_rawDescGZIP(), []int{5}
}

func (x *Net_Inbox_DeleteEmailReq) GetEmailIds() []int32 {
	if x != nil {
		return x.EmailIds
	}
	return nil
}

type Net_Inbox_DeleteEmailRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"` //0:成功;1:失败;
}

func (x *Net_Inbox_DeleteEmailRet) Reset() {
	*x = Net_Inbox_DeleteEmailRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Inbox_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Inbox_DeleteEmailRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Inbox_DeleteEmailRet) ProtoMessage() {}

func (x *Net_Inbox_DeleteEmailRet) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Inbox_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Inbox_DeleteEmailRet.ProtoReflect.Descriptor instead.
func (*Net_Inbox_DeleteEmailRet) Descriptor() ([]byte, []int) {
	return file_Net_Inbox_proto_rawDescGZIP(), []int{6}
}

func (x *Net_Inbox_DeleteEmailRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

// 收件箱->领取奖励礼物
type Net_Inbox_ClaimRewardGiftsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailId int32 `protobuf:"varint,1,opt,name=EmailId,proto3" json:"EmailId,omitempty"` //邮件Id
}

func (x *Net_Inbox_ClaimRewardGiftsReq) Reset() {
	*x = Net_Inbox_ClaimRewardGiftsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Inbox_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Inbox_ClaimRewardGiftsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Inbox_ClaimRewardGiftsReq) ProtoMessage() {}

func (x *Net_Inbox_ClaimRewardGiftsReq) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Inbox_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Inbox_ClaimRewardGiftsReq.ProtoReflect.Descriptor instead.
func (*Net_Inbox_ClaimRewardGiftsReq) Descriptor() ([]byte, []int) {
	return file_Net_Inbox_proto_rawDescGZIP(), []int{7}
}

func (x *Net_Inbox_ClaimRewardGiftsReq) GetEmailId() int32 {
	if x != nil {
		return x.EmailId
	}
	return 0
}

type Net_Inbox_ClaimRewardGiftsRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"` //0:成功;1:未知错我;2:;
}

func (x *Net_Inbox_ClaimRewardGiftsRet) Reset() {
	*x = Net_Inbox_ClaimRewardGiftsRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Inbox_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Inbox_ClaimRewardGiftsRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Inbox_ClaimRewardGiftsRet) ProtoMessage() {}

func (x *Net_Inbox_ClaimRewardGiftsRet) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Inbox_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Inbox_ClaimRewardGiftsRet.ProtoReflect.Descriptor instead.
func (*Net_Inbox_ClaimRewardGiftsRet) Descriptor() ([]byte, []int) {
	return file_Net_Inbox_proto_rawDescGZIP(), []int{8}
}

func (x *Net_Inbox_ClaimRewardGiftsRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

// 获取礼物列表
type Net_Inbox_GetInboxListRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InboxItemInfoList map[int32]*Base_Inbox_InboxItemInfo `protobuf:"bytes,1,rep,name=InboxItemInfoList,proto3" json:"InboxItemInfoList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //玩家收件箱 邮件列表
}

func (x *Net_Inbox_GetInboxListRet) Reset() {
	*x = Net_Inbox_GetInboxListRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Inbox_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Inbox_GetInboxListRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Inbox_GetInboxListRet) ProtoMessage() {}

func (x *Net_Inbox_GetInboxListRet) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Inbox_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Inbox_GetInboxListRet.ProtoReflect.Descriptor instead.
func (*Net_Inbox_GetInboxListRet) Descriptor() ([]byte, []int) {
	return file_Net_Inbox_proto_rawDescGZIP(), []int{9}
}

func (x *Net_Inbox_GetInboxListRet) GetInboxItemInfoList() map[int32]*Base_Inbox_InboxItemInfo {
	if x != nil {
		return x.InboxItemInfoList
	}
	return nil
}

// 获取邮件礼包
type Net_Inbox_ReceiveGiftsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"` //邮件Id
}

func (x *Net_Inbox_ReceiveGiftsReq) Reset() {
	*x = Net_Inbox_ReceiveGiftsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Inbox_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Inbox_ReceiveGiftsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Inbox_ReceiveGiftsReq) ProtoMessage() {}

func (x *Net_Inbox_ReceiveGiftsReq) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Inbox_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Inbox_ReceiveGiftsReq.ProtoReflect.Descriptor instead.
func (*Net_Inbox_ReceiveGiftsReq) Descriptor() ([]byte, []int) {
	return file_Net_Inbox_proto_rawDescGZIP(), []int{10}
}

func (x *Net_Inbox_ReceiveGiftsReq) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 获取邮件礼包
type Net_Inbox_ReceiveGiftsRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"` //0:成功;1:失败;
}

func (x *Net_Inbox_ReceiveGiftsRet) Reset() {
	*x = Net_Inbox_ReceiveGiftsRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Inbox_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Inbox_ReceiveGiftsRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Inbox_ReceiveGiftsRet) ProtoMessage() {}

func (x *Net_Inbox_ReceiveGiftsRet) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Inbox_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Inbox_ReceiveGiftsRet.ProtoReflect.Descriptor instead.
func (*Net_Inbox_ReceiveGiftsRet) Descriptor() ([]byte, []int) {
	return file_Net_Inbox_proto_rawDescGZIP(), []int{11}
}

func (x *Net_Inbox_ReceiveGiftsRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

var File_Net_Inbox_proto protoreflect.FileDescriptor

var file_Net_Inbox_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x4e, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x50, 0x62, 0x22, 0x50, 0x0a, 0x14, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x49, 0x6e,
	0x62, 0x6f, 0x78, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x38, 0x0a,
	0x08, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x50, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x5f,
	0x49, 0x6e, 0x62, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x49,
	0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xba, 0x03, 0x0a, 0x18, 0x42, 0x61, 0x73, 0x65,
	0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x49, 0x73, 0x52, 0x65, 0x61, 0x64, 0x12, 0x24, 0x0a, 0x0d,
	0x49, 0x73, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0d, 0x49, 0x73, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x31, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x31, 0x12, 0x1a, 0x0a, 0x08,
	0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x31, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x32, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x32, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x32, 0x12, 0x18,
	0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x33, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x33, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d,
	0x4e, 0x75, 0x6d, 0x33, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x49, 0x74, 0x65, 0x6d,
	0x4e, 0x75, 0x6d, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x73, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x54, 0x73, 0x22, 0xdd, 0x01, 0x0a, 0x1c, 0x4e, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x62,
	0x6f, 0x78, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x74, 0x12, 0x5c, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e,
	0x50, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x5f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x74, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x1a, 0x5f, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x32, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x50, 0x62,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x5f, 0x49, 0x6e, 0x62, 0x6f,
	0x78, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x5c, 0x0a, 0x16, 0x4e, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x62, 0x6f,
	0x78, 0x5f, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x42,
	0x0a, 0x0d, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x50, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x5f,
	0x49, 0x6e, 0x62, 0x6f, 0x78, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x2a, 0x0a, 0x16, 0x4e, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x5f,
	0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0x36,
	0x0a, 0x18, 0x4e, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x5f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x2c, 0x0a, 0x18, 0x4e, 0x65, 0x74, 0x5f, 0x49, 0x6e,
	0x62, 0x6f, 0x78, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x52, 0x65, 0x74, 0x22, 0x39, 0x0a, 0x1d, 0x4e, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x62, 0x6f,
	0x78, 0x5f, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x47, 0x69, 0x66,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x22,
	0x31, 0x0a, 0x1d, 0x4e, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x5f, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52,
	0x65, 0x74, 0x22, 0xe3, 0x01, 0x0a, 0x19, 0x4e, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78,
	0x5f, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x74,
	0x12, 0x62, 0x0a, 0x11, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x50, 0x62,
	0x2e, 0x4e, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x5f, 0x47, 0x65, 0x74, 0x49, 0x6e,
	0x62, 0x6f, 0x78, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x74, 0x2e, 0x49, 0x6e, 0x62, 0x6f, 0x78,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x11, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x4c, 0x69, 0x73, 0x74, 0x1a, 0x62, 0x0a, 0x16, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x49, 0x74, 0x65,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x32, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x50, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x5f,
	0x49, 0x6e, 0x62, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x31, 0x0a, 0x19, 0x4e, 0x65, 0x74, 0x5f,
	0x49, 0x6e, 0x62, 0x6f, 0x78, 0x5f, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x47, 0x69, 0x66,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x2d, 0x0a, 0x19, 0x4e,
	0x65, 0x74, 0x5f, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x5f, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x2a, 0x2c, 0x0a, 0x09, 0x49, 0x6e,
	0x62, 0x6f, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x6e, 0x62, 0x6f, 0x78,
	0x49, 0x64, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x54,
	0x79, 0x70, 0x65, 0x53, 0x79, 0x73, 0x10, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Net_Inbox_proto_rawDescOnce sync.Once
	file_Net_Inbox_proto_rawDescData = file_Net_Inbox_proto_rawDesc
)

func file_Net_Inbox_proto_rawDescGZIP() []byte {
	file_Net_Inbox_proto_rawDescOnce.Do(func() {
		file_Net_Inbox_proto_rawDescData = protoimpl.X.CompressGZIP(file_Net_Inbox_proto_rawDescData)
	})
	return file_Net_Inbox_proto_rawDescData
}

var file_Net_Inbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Net_Inbox_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_Net_Inbox_proto_goTypes = []interface{}{
	(InboxType)(0),                        // 0: Pb.InboxType
	(*Base_Inbox_InboxInfo)(nil),          // 1: Pb.Base_Inbox_InboxInfo
	(*Base_Inbox_InboxItemInfo)(nil),      // 2: Pb.Base_Inbox_InboxItemInfo
	(*Net_Inbox_UpdateItemsInfoRet)(nil),  // 3: Pb.Net_Inbox_UpdateItemsInfoRet
	(*Net_Inbox_SendEmailReq)(nil),        // 4: Pb.Net_Inbox_SendEmailReq
	(*Net_Inbox_SendEmailRet)(nil),        // 5: Pb.Net_Inbox_SendEmailRet
	(*Net_Inbox_DeleteEmailReq)(nil),      // 6: Pb.Net_Inbox_DeleteEmailReq
	(*Net_Inbox_DeleteEmailRet)(nil),      // 7: Pb.Net_Inbox_DeleteEmailRet
	(*Net_Inbox_ClaimRewardGiftsReq)(nil), // 8: Pb.Net_Inbox_ClaimRewardGiftsReq
	(*Net_Inbox_ClaimRewardGiftsRet)(nil), // 9: Pb.Net_Inbox_ClaimRewardGiftsRet
	(*Net_Inbox_GetInboxListRet)(nil),     // 10: Pb.Net_Inbox_GetInboxListRet
	(*Net_Inbox_ReceiveGiftsReq)(nil),     // 11: Pb.Net_Inbox_ReceiveGiftsReq
	(*Net_Inbox_ReceiveGiftsRet)(nil),     // 12: Pb.Net_Inbox_ReceiveGiftsRet
	nil,                                   // 13: Pb.Net_Inbox_UpdateItemsInfoRet.UpdateItemListEntry
	nil,                                   // 14: Pb.Net_Inbox_GetInboxListRet.InboxItemInfoListEntry
}
var file_Net_Inbox_proto_depIdxs = []int32{
	2,  // 0: Pb.Base_Inbox_InboxInfo.ItemList:type_name -> Pb.Base_Inbox_InboxItemInfo
	13, // 1: Pb.Net_Inbox_UpdateItemsInfoRet.UpdateItemList:type_name -> Pb.Net_Inbox_UpdateItemsInfoRet.UpdateItemListEntry
	2,  // 2: Pb.Net_Inbox_SendEmailReq.InboxItemInfo:type_name -> Pb.Base_Inbox_InboxItemInfo
	14, // 3: Pb.Net_Inbox_GetInboxListRet.InboxItemInfoList:type_name -> Pb.Net_Inbox_GetInboxListRet.InboxItemInfoListEntry
	2,  // 4: Pb.Net_Inbox_UpdateItemsInfoRet.UpdateItemListEntry.value:type_name -> Pb.Base_Inbox_InboxItemInfo
	2,  // 5: Pb.Net_Inbox_GetInboxListRet.InboxItemInfoListEntry.value:type_name -> Pb.Base_Inbox_InboxItemInfo
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_Net_Inbox_proto_init() }
func file_Net_Inbox_proto_init() {
	if File_Net_Inbox_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Net_Inbox_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Base_Inbox_InboxInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Inbox_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Base_Inbox_InboxItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Inbox_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Inbox_UpdateItemsInfoRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Inbox_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Inbox_SendEmailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Inbox_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Inbox_SendEmailRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Inbox_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Inbox_DeleteEmailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Inbox_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Inbox_DeleteEmailRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Inbox_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Inbox_ClaimRewardGiftsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Inbox_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Inbox_ClaimRewardGiftsRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Inbox_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Inbox_GetInboxListRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Inbox_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Inbox_ReceiveGiftsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Net_Inbox_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Inbox_ReceiveGiftsRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Net_Inbox_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Net_Inbox_proto_goTypes,
		DependencyIndexes: file_Net_Inbox_proto_depIdxs,
		EnumInfos:         file_Net_Inbox_proto_enumTypes,
		MessageInfos:      file_Net_Inbox_proto_msgTypes,
	}.Build()
	File_Net_Inbox_proto = out.File
	file_Net_Inbox_proto_rawDesc = nil
	file_Net_Inbox_proto_goTypes = nil
	file_Net_Inbox_proto_depIdxs = nil
}
