// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.1
// source: Net_Lobby_User.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 大厅->用户
//
// added by yh @ 2024/01/26 14:36
// 注意:
type Base_Lobby_UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base_Lobby_UserInfo) Reset() {
	*x = Base_Lobby_UserInfo{}
	mi := &file_Net_Lobby_User_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base_Lobby_UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base_Lobby_UserInfo) ProtoMessage() {}

func (x *Base_Lobby_UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Lobby_User_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base_Lobby_UserInfo.ProtoReflect.Descriptor instead.
func (*Base_Lobby_UserInfo) Descriptor() ([]byte, []int) {
	return file_Net_Lobby_User_proto_rawDescGZIP(), []int{0}
}

var File_Net_Lobby_User_proto protoreflect.FileDescriptor

const file_Net_Lobby_User_proto_rawDesc = "" +
	"\n" +
	"\x14Net_Lobby_User.proto\x12\x02Pb\"\x15\n" +
	"\x13Base_Lobby_UserInfoB\x06Z\x04./pbb\x06proto3"

var (
	file_Net_Lobby_User_proto_rawDescOnce sync.Once
	file_Net_Lobby_User_proto_rawDescData []byte
)

func file_Net_Lobby_User_proto_rawDescGZIP() []byte {
	file_Net_Lobby_User_proto_rawDescOnce.Do(func() {
		file_Net_Lobby_User_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Net_Lobby_User_proto_rawDesc), len(file_Net_Lobby_User_proto_rawDesc)))
	})
	return file_Net_Lobby_User_proto_rawDescData
}

var file_Net_Lobby_User_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Net_Lobby_User_proto_goTypes = []any{
	(*Base_Lobby_UserInfo)(nil), // 0: Pb.Base_Lobby_UserInfo
}
var file_Net_Lobby_User_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Net_Lobby_User_proto_init() }
func file_Net_Lobby_User_proto_init() {
	if File_Net_Lobby_User_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Net_Lobby_User_proto_rawDesc), len(file_Net_Lobby_User_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Net_Lobby_User_proto_goTypes,
		DependencyIndexes: file_Net_Lobby_User_proto_depIdxs,
		MessageInfos:      file_Net_Lobby_User_proto_msgTypes,
	}.Build()
	File_Net_Lobby_User_proto = out.File
	file_Net_Lobby_User_proto_goTypes = nil
	file_Net_Lobby_User_proto_depIdxs = nil
}
