// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.1
// source: Proto.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceHolder3333 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dec           string                 `protobuf:"bytes,1,opt,name=dec,proto3" json:"dec,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Flag          bool                   `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
	FunID         int32                  `protobuf:"varint,4,opt,name=funID,proto3" json:"funID,omitempty"`
	Cards         []int32                `protobuf:"varint,5,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceHolder3333) Reset() {
	*x = PlaceHolder3333{}
	mi := &file_Proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceHolder3333) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceHolder3333) ProtoMessage() {}

func (x *PlaceHolder3333) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceHolder3333.ProtoReflect.Descriptor instead.
func (*PlaceHolder3333) Descriptor() ([]byte, []int) {
	return file_Proto_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceHolder3333) GetDec() string {
	if x != nil {
		return x.Dec
	}
	return ""
}

func (x *PlaceHolder3333) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PlaceHolder3333) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *PlaceHolder3333) GetFunID() int32 {
	if x != nil {
		return x.FunID
	}
	return 0
}

func (x *PlaceHolder3333) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

type AvatarInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Money         int32                  `protobuf:"varint,3,opt,name=money,proto3" json:"money,omitempty"`
	TeamId        int32                  `protobuf:"varint,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Cards         []int32                `protobuf:"varint,5,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarInfo) Reset() {
	*x = AvatarInfo{}
	mi := &file_Proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarInfo) ProtoMessage() {}

func (x *AvatarInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarInfo.ProtoReflect.Descriptor instead.
func (*AvatarInfo) Descriptor() ([]byte, []int) {
	return file_Proto_proto_rawDescGZIP(), []int{1}
}

func (x *AvatarInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AvatarInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AvatarInfo) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *AvatarInfo) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *AvatarInfo) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

type MatchingSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarInfos   map[int32]*AvatarInfo  `protobuf:"bytes,1,rep,name=AvatarInfos,proto3" json:"AvatarInfos,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchingSuccess) Reset() {
	*x = MatchingSuccess{}
	mi := &file_Proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingSuccess) ProtoMessage() {}

func (x *MatchingSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingSuccess.ProtoReflect.Descriptor instead.
func (*MatchingSuccess) Descriptor() ([]byte, []int) {
	return file_Proto_proto_rawDescGZIP(), []int{2}
}

func (x *MatchingSuccess) GetAvatarInfos() map[int32]*AvatarInfo {
	if x != nil {
		return x.AvatarInfos
	}
	return nil
}

type PlayedCardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int32                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	CardValue     int32                  `protobuf:"varint,3,opt,name=card_value,json=cardValue,proto3" json:"card_value,omitempty"`
	OutCardValue  int32                  `protobuf:"varint,4,opt,name=out_card_value,json=outCardValue,proto3" json:"out_card_value,omitempty"`
	CardsLeftNum  int32                  `protobuf:"varint,5,opt,name=cards_left_num,json=cardsLeftNum,proto3" json:"cards_left_num,omitempty"`
	AvatarInfos   map[int32]*AvatarInfo  `protobuf:"bytes,6,rep,name=AvatarInfos,proto3" json:"AvatarInfos,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayedCardInfo) Reset() {
	*x = PlayedCardInfo{}
	mi := &file_Proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayedCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayedCardInfo) ProtoMessage() {}

func (x *PlayedCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayedCardInfo.ProtoReflect.Descriptor instead.
func (*PlayedCardInfo) Descriptor() ([]byte, []int) {
	return file_Proto_proto_rawDescGZIP(), []int{3}
}

func (x *PlayedCardInfo) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *PlayedCardInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PlayedCardInfo) GetCardValue() int32 {
	if x != nil {
		return x.CardValue
	}
	return 0
}

func (x *PlayedCardInfo) GetOutCardValue() int32 {
	if x != nil {
		return x.OutCardValue
	}
	return 0
}

func (x *PlayedCardInfo) GetCardsLeftNum() int32 {
	if x != nil {
		return x.CardsLeftNum
	}
	return 0
}

func (x *PlayedCardInfo) GetAvatarInfos() map[int32]*AvatarInfo {
	if x != nil {
		return x.AvatarInfos
	}
	return nil
}

var File_Proto_proto protoreflect.FileDescriptor

const file_Proto_proto_rawDesc = "" +
	"\n" +
	"\vProto.proto\x12\x02Pb\"}\n" +
	"\x0fPlaceHolder3333\x12\x10\n" +
	"\x03dec\x18\x01 \x01(\tR\x03dec\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x12\n" +
	"\x04flag\x18\x03 \x01(\bR\x04flag\x12\x14\n" +
	"\x05funID\x18\x04 \x01(\x05R\x05funID\x12\x14\n" +
	"\x05cards\x18\x05 \x03(\x05R\x05cards\"\x7f\n" +
	"\n" +
	"AvatarInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x14\n" +
	"\x05money\x18\x03 \x01(\x05R\x05money\x12\x17\n" +
	"\ateam_id\x18\x04 \x01(\x05R\x06teamId\x12\x14\n" +
	"\x05cards\x18\x05 \x03(\x05R\x05cards\"\xa9\x01\n" +
	"\x0fMatchingSuccess\x12F\n" +
	"\vAvatarInfos\x18\x01 \x03(\v2$.Pb.MatchingSuccess.AvatarInfosEntryR\vAvatarInfos\x1aN\n" +
	"\x10AvatarInfosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.Pb.AvatarInfoR\x05value:\x028\x01\"\xc5\x02\n" +
	"\x0ePlayedCardInfo\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x05R\x06teamId\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x1d\n" +
	"\n" +
	"card_value\x18\x03 \x01(\x05R\tcardValue\x12$\n" +
	"\x0eout_card_value\x18\x04 \x01(\x05R\foutCardValue\x12$\n" +
	"\x0ecards_left_num\x18\x05 \x01(\x05R\fcardsLeftNum\x12E\n" +
	"\vAvatarInfos\x18\x06 \x03(\v2#.Pb.PlayedCardInfo.AvatarInfosEntryR\vAvatarInfos\x1aN\n" +
	"\x10AvatarInfosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.Pb.AvatarInfoR\x05value:\x028\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_Proto_proto_rawDescOnce sync.Once
	file_Proto_proto_rawDescData []byte
)

func file_Proto_proto_rawDescGZIP() []byte {
	file_Proto_proto_rawDescOnce.Do(func() {
		file_Proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Proto_proto_rawDesc), len(file_Proto_proto_rawDesc)))
	})
	return file_Proto_proto_rawDescData
}

var file_Proto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Proto_proto_goTypes = []any{
	(*PlaceHolder3333)(nil), // 0: Pb.PlaceHolder3333
	(*AvatarInfo)(nil),      // 1: Pb.AvatarInfo
	(*MatchingSuccess)(nil), // 2: Pb.MatchingSuccess
	(*PlayedCardInfo)(nil),  // 3: Pb.PlayedCardInfo
	nil,                     // 4: Pb.MatchingSuccess.AvatarInfosEntry
	nil,                     // 5: Pb.PlayedCardInfo.AvatarInfosEntry
}
var file_Proto_proto_depIdxs = []int32{
	4, // 0: Pb.MatchingSuccess.AvatarInfos:type_name -> Pb.MatchingSuccess.AvatarInfosEntry
	5, // 1: Pb.PlayedCardInfo.AvatarInfos:type_name -> Pb.PlayedCardInfo.AvatarInfosEntry
	1, // 2: Pb.MatchingSuccess.AvatarInfosEntry.value:type_name -> Pb.AvatarInfo
	1, // 3: Pb.PlayedCardInfo.AvatarInfosEntry.value:type_name -> Pb.AvatarInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Proto_proto_init() }
func file_Proto_proto_init() {
	if File_Proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Proto_proto_rawDesc), len(file_Proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Proto_proto_goTypes,
		DependencyIndexes: file_Proto_proto_depIdxs,
		MessageInfos:      file_Proto_proto_msgTypes,
	}.Build()
	File_Proto_proto = out.File
	file_Proto_proto_goTypes = nil
	file_Proto_proto_depIdxs = nil
}
