// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.1
// source: sys_admin_cmd.proto

package pb_admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cmd int32

const (
	Cmd_Admin_Idle                        Cmd = 0       //空置占位没用
	Cmd_Admin_GetSystem                   Cmd = 9001001 //返回服务器信息
	Cmd_Admin_UpdateConfig                Cmd = 9001002 //更新配置
	Cmd_Admin_UserAddCurrency             Cmd = 9001003 //user添加货币
	Cmd_Admin_ExecuteEmail                Cmd = 9001004 //执行邮件
	Cmd_Admin_GetUsers                    Cmd = 9001005 //获取用户列表
	Cmd_Admin_DeleteAccount               Cmd = 9001006 //删除账号
	Cmd_Admin_AddPlayerInbox              Cmd = 9001007 //添加玩家邮件
	Cmd_Admin_DeleteRole                  Cmd = 9001008 //删除角色
	Cmd_DeleteAllRoleRedisData            Cmd = 9001009 //删除所有角色数据
	Cmd_Admin_Cheat                       Cmd = 9001011 //作弊
	Cmd_Admin_DeleteRedisAllRoleCacheData Cmd = 9001012 //删除所有Redis角色缓存数据
)

// Enum value maps for Cmd.
var (
	Cmd_name = map[int32]string{
		0:       "Admin_Idle",
		9001001: "Admin_GetSystem",
		9001002: "Admin_UpdateConfig",
		9001003: "Admin_UserAddCurrency",
		9001004: "Admin_ExecuteEmail",
		9001005: "Admin_GetUsers",
		9001006: "Admin_DeleteAccount",
		9001007: "Admin_AddPlayerInbox",
		9001008: "Admin_DeleteRole",
		9001009: "DeleteAllRoleRedisData",
		9001011: "Admin_Cheat",
		9001012: "Admin_DeleteRedisAllRoleCacheData",
	}
	Cmd_value = map[string]int32{
		"Admin_Idle":                        0,
		"Admin_GetSystem":                   9001001,
		"Admin_UpdateConfig":                9001002,
		"Admin_UserAddCurrency":             9001003,
		"Admin_ExecuteEmail":                9001004,
		"Admin_GetUsers":                    9001005,
		"Admin_DeleteAccount":               9001006,
		"Admin_AddPlayerInbox":              9001007,
		"Admin_DeleteRole":                  9001008,
		"DeleteAllRoleRedisData":            9001009,
		"Admin_Cheat":                       9001011,
		"Admin_DeleteRedisAllRoleCacheData": 9001012,
	}
)

func (x Cmd) Enum() *Cmd {
	p := new(Cmd)
	*p = x
	return p
}

func (x Cmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cmd) Descriptor() protoreflect.EnumDescriptor {
	return file_sys_admin_cmd_proto_enumTypes[0].Descriptor()
}

func (Cmd) Type() protoreflect.EnumType {
	return &file_sys_admin_cmd_proto_enumTypes[0]
}

func (x Cmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cmd.Descriptor instead.
func (Cmd) EnumDescriptor() ([]byte, []int) {
	return file_sys_admin_cmd_proto_rawDescGZIP(), []int{0}
}

var File_sys_admin_cmd_proto protoreflect.FileDescriptor

const file_sys_admin_cmd_proto_rawDesc = "" +
	"\n" +
	"\x13sys_admin_cmd.proto\x12\bpb_admin*\xc7\x02\n" +
	"\x03Cmd\x12\x0e\n" +
	"\n" +
	"Admin_Idle\x10\x00\x12\x16\n" +
	"\x0fAdmin_GetSystem\x10\xa9\xb0\xa5\x04\x12\x19\n" +
	"\x12Admin_UpdateConfig\x10\xaa\xb0\xa5\x04\x12\x1c\n" +
	"\x15Admin_UserAddCurrency\x10\xab\xb0\xa5\x04\x12\x19\n" +
	"\x12Admin_ExecuteEmail\x10\xac\xb0\xa5\x04\x12\x15\n" +
	"\x0eAdmin_GetUsers\x10\xad\xb0\xa5\x04\x12\x1a\n" +
	"\x13Admin_DeleteAccount\x10\xae\xb0\xa5\x04\x12\x1b\n" +
	"\x14Admin_AddPlayerInbox\x10\xaf\xb0\xa5\x04\x12\x17\n" +
	"\x10Admin_DeleteRole\x10\xb0\xb0\xa5\x04\x12\x1d\n" +
	"\x16DeleteAllRoleRedisData\x10\xb1\xb0\xa5\x04\x12\x12\n" +
	"\vAdmin_Cheat\x10\xb3\xb0\xa5\x04\x12(\n" +
	"!Admin_DeleteRedisAllRoleCacheData\x10\xb4\xb0\xa5\x04B\fZ\n" +
	"./pb_adminb\x06proto3"

var (
	file_sys_admin_cmd_proto_rawDescOnce sync.Once
	file_sys_admin_cmd_proto_rawDescData []byte
)

func file_sys_admin_cmd_proto_rawDescGZIP() []byte {
	file_sys_admin_cmd_proto_rawDescOnce.Do(func() {
		file_sys_admin_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sys_admin_cmd_proto_rawDesc), len(file_sys_admin_cmd_proto_rawDesc)))
	})
	return file_sys_admin_cmd_proto_rawDescData
}

var file_sys_admin_cmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sys_admin_cmd_proto_goTypes = []any{
	(Cmd)(0), // 0: pb_admin.Cmd
}
var file_sys_admin_cmd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sys_admin_cmd_proto_init() }
func file_sys_admin_cmd_proto_init() {
	if File_sys_admin_cmd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sys_admin_cmd_proto_rawDesc), len(file_sys_admin_cmd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_admin_cmd_proto_goTypes,
		DependencyIndexes: file_sys_admin_cmd_proto_depIdxs,
		EnumInfos:         file_sys_admin_cmd_proto_enumTypes,
	}.Build()
	File_sys_admin_cmd_proto = out.File
	file_sys_admin_cmd_proto_goTypes = nil
	file_sys_admin_cmd_proto_depIdxs = nil
}
