// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.23.1
// source: sys_admin_protocol.proto

package pb_admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 游戏服务器基本信息
type Base_Admin_SystemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏服务器Id
	// 在线人数
	OnlineNum int32 `protobuf:"varint,1,opt,name=OnlineNum,proto3" json:"OnlineNum,omitempty"`
	// 总连接数
	TotalConnectNum int32 `protobuf:"varint,2,opt,name=TotalConnectNum,proto3" json:"TotalConnectNum,omitempty"`
}

func (x *Base_Admin_SystemInfo) Reset() {
	*x = Base_Admin_SystemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Base_Admin_SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base_Admin_SystemInfo) ProtoMessage() {}

func (x *Base_Admin_SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base_Admin_SystemInfo.ProtoReflect.Descriptor instead.
func (*Base_Admin_SystemInfo) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Base_Admin_SystemInfo) GetOnlineNum() int32 {
	if x != nil {
		return x.OnlineNum
	}
	return 0
}

func (x *Base_Admin_SystemInfo) GetTotalConnectNum() int32 {
	if x != nil {
		return x.TotalConnectNum
	}
	return 0
}

// 获取游戏服务器基本信息
type Net_Admin_GetSystemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Net_Admin_GetSystemReq) Reset() {
	*x = Net_Admin_GetSystemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_GetSystemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_GetSystemReq) ProtoMessage() {}

func (x *Net_Admin_GetSystemReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_GetSystemReq.ProtoReflect.Descriptor instead.
func (*Net_Admin_GetSystemReq) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{1}
}

type Net_Admin_GetSystemRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret        int32                  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`              //0:成功;1:失败;
	SystemInfo *Base_Admin_SystemInfo `protobuf:"bytes,2,opt,name=SystemInfo,proto3" json:"SystemInfo,omitempty"` //游戏服务器基本信息
}

func (x *Net_Admin_GetSystemRet) Reset() {
	*x = Net_Admin_GetSystemRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_GetSystemRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_GetSystemRet) ProtoMessage() {}

func (x *Net_Admin_GetSystemRet) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_GetSystemRet.ProtoReflect.Descriptor instead.
func (*Net_Admin_GetSystemRet) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *Net_Admin_GetSystemRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *Net_Admin_GetSystemRet) GetSystemInfo() *Base_Admin_SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

// 获取当前在线玩家列表
type Net_Admin_GetUsersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Net_Admin_GetUsersReq) Reset() {
	*x = Net_Admin_GetUsersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_GetUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_GetUsersReq) ProtoMessage() {}

func (x *Net_Admin_GetUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_GetUsersReq.ProtoReflect.Descriptor instead.
func (*Net_Admin_GetUsersReq) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{3}
}

type Net_Admin_GetUsersRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"` //0:成功;1:失败;
}

func (x *Net_Admin_GetUsersRet) Reset() {
	*x = Net_Admin_GetUsersRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_GetUsersRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_GetUsersRet) ProtoMessage() {}

func (x *Net_Admin_GetUsersRet) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_GetUsersRet.ProtoReflect.Descriptor instead.
func (*Net_Admin_GetUsersRet) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *Net_Admin_GetUsersRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

// 获取游戏服务器基本信息
type Net_Admin_UpdateConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Net_Admin_UpdateConfigReq) Reset() {
	*x = Net_Admin_UpdateConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_UpdateConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_UpdateConfigReq) ProtoMessage() {}

func (x *Net_Admin_UpdateConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_UpdateConfigReq.ProtoReflect.Descriptor instead.
func (*Net_Admin_UpdateConfigReq) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{5}
}

type Net_Admin_UpdateConfigRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"` //0:成功;1:失败;
}

func (x *Net_Admin_UpdateConfigRet) Reset() {
	*x = Net_Admin_UpdateConfigRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_UpdateConfigRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_UpdateConfigRet) ProtoMessage() {}

func (x *Net_Admin_UpdateConfigRet) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_UpdateConfigRet.ProtoReflect.Descriptor instead.
func (*Net_Admin_UpdateConfigRet) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *Net_Admin_UpdateConfigRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

// 获取游戏服务器基本信息
type Net_Admin_UserAddCurrencyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"` //玩家Id
	Coin   int32  `protobuf:"varint,2,opt,name=Coin,proto3" json:"Coin,omitempty"`    //金币
	Gold   int32  `protobuf:"varint,3,opt,name=Gold,proto3" json:"Gold,omitempty"`    //钻石
}

func (x *Net_Admin_UserAddCurrencyReq) Reset() {
	*x = Net_Admin_UserAddCurrencyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_UserAddCurrencyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_UserAddCurrencyReq) ProtoMessage() {}

func (x *Net_Admin_UserAddCurrencyReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_UserAddCurrencyReq.ProtoReflect.Descriptor instead.
func (*Net_Admin_UserAddCurrencyReq) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *Net_Admin_UserAddCurrencyReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Net_Admin_UserAddCurrencyReq) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *Net_Admin_UserAddCurrencyReq) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type Net_Admin_UserAddCurrencyRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret             int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`                         //0:成功;1:失败;
	UserCurrentCoin int32 `protobuf:"varint,4,opt,name=UserCurrentCoin,proto3" json:"UserCurrentCoin,omitempty"` //玩家当前金币
	UserCurrentGold int32 `protobuf:"varint,5,opt,name=UserCurrentGold,proto3" json:"UserCurrentGold,omitempty"` //玩家当前钻石
}

func (x *Net_Admin_UserAddCurrencyRet) Reset() {
	*x = Net_Admin_UserAddCurrencyRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_UserAddCurrencyRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_UserAddCurrencyRet) ProtoMessage() {}

func (x *Net_Admin_UserAddCurrencyRet) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_UserAddCurrencyRet.ProtoReflect.Descriptor instead.
func (*Net_Admin_UserAddCurrencyRet) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *Net_Admin_UserAddCurrencyRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *Net_Admin_UserAddCurrencyRet) GetUserCurrentCoin() int32 {
	if x != nil {
		return x.UserCurrentCoin
	}
	return 0
}

func (x *Net_Admin_UserAddCurrencyRet) GetUserCurrentGold() int32 {
	if x != nil {
		return x.UserCurrentGold
	}
	return 0
}

// 执行一封邮件 System
type Net_Admin_ExecuteEmailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailType int32  `protobuf:"varint,1,opt,name=EmailType,proto3" json:"EmailType,omitempty"` //0:普通邮件;1:系统邮件;2:;3:;
	Title     string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`          //邮件标题
	Content   string `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`      //邮件内容
	// 礼包Id
	GiftId string `protobuf:"bytes,4,opt,name=GiftId,proto3" json:"GiftId,omitempty"`
}

func (x *Net_Admin_ExecuteEmailReq) Reset() {
	*x = Net_Admin_ExecuteEmailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_ExecuteEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_ExecuteEmailReq) ProtoMessage() {}

func (x *Net_Admin_ExecuteEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_ExecuteEmailReq.ProtoReflect.Descriptor instead.
func (*Net_Admin_ExecuteEmailReq) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *Net_Admin_ExecuteEmailReq) GetEmailType() int32 {
	if x != nil {
		return x.EmailType
	}
	return 0
}

func (x *Net_Admin_ExecuteEmailReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Net_Admin_ExecuteEmailReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Net_Admin_ExecuteEmailReq) GetGiftId() string {
	if x != nil {
		return x.GiftId
	}
	return ""
}

type Net_Admin_ExecuteEmailRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"` //0:成功;1:失败;
}

func (x *Net_Admin_ExecuteEmailRet) Reset() {
	*x = Net_Admin_ExecuteEmailRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_ExecuteEmailRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_ExecuteEmailRet) ProtoMessage() {}

func (x *Net_Admin_ExecuteEmailRet) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_ExecuteEmailRet.ProtoReflect.Descriptor instead.
func (*Net_Admin_ExecuteEmailRet) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *Net_Admin_ExecuteEmailRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type Net_Admin_DeleteRedisAllRoleCacheDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Net_Admin_DeleteRedisAllRoleCacheDataReq) Reset() {
	*x = Net_Admin_DeleteRedisAllRoleCacheDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_DeleteRedisAllRoleCacheDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_DeleteRedisAllRoleCacheDataReq) ProtoMessage() {}

func (x *Net_Admin_DeleteRedisAllRoleCacheDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_DeleteRedisAllRoleCacheDataReq.ProtoReflect.Descriptor instead.
func (*Net_Admin_DeleteRedisAllRoleCacheDataReq) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{11}
}

type Net_Admin_DeleteRedisAllRoleCacheDataRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"` //0:成功;1:失败;
}

func (x *Net_Admin_DeleteRedisAllRoleCacheDataRet) Reset() {
	*x = Net_Admin_DeleteRedisAllRoleCacheDataRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_DeleteRedisAllRoleCacheDataRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_DeleteRedisAllRoleCacheDataRet) ProtoMessage() {}

func (x *Net_Admin_DeleteRedisAllRoleCacheDataRet) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_DeleteRedisAllRoleCacheDataRet.ProtoReflect.Descriptor instead.
func (*Net_Admin_DeleteRedisAllRoleCacheDataRet) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *Net_Admin_DeleteRedisAllRoleCacheDataRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

// 作弊
type Net_Admin_CheatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Net_Admin_CheatReq) Reset() {
	*x = Net_Admin_CheatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_CheatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_CheatReq) ProtoMessage() {}

func (x *Net_Admin_CheatReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_CheatReq.ProtoReflect.Descriptor instead.
func (*Net_Admin_CheatReq) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{13}
}

type Net_Admin_CheatRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Net_Admin_CheatRet) Reset() {
	*x = Net_Admin_CheatRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_CheatRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_CheatRet) ProtoMessage() {}

func (x *Net_Admin_CheatRet) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_CheatRet.ProtoReflect.Descriptor instead.
func (*Net_Admin_CheatRet) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{14}
}

// 删除玩家账号
type Net_Admin_DeleteAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Net_Admin_DeleteAccountReq) Reset() {
	*x = Net_Admin_DeleteAccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_DeleteAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_DeleteAccountReq) ProtoMessage() {}

func (x *Net_Admin_DeleteAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_DeleteAccountReq.ProtoReflect.Descriptor instead.
func (*Net_Admin_DeleteAccountReq) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{15}
}

type Net_Admin_DeleteAccountRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Net_Admin_DeleteAccountRet) Reset() {
	*x = Net_Admin_DeleteAccountRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_DeleteAccountRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_DeleteAccountRet) ProtoMessage() {}

func (x *Net_Admin_DeleteAccountRet) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_DeleteAccountRet.ProtoReflect.Descriptor instead.
func (*Net_Admin_DeleteAccountRet) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{16}
}

// 添加玩家金币
type Net_Admin_AddPlayerCoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PId     string `protobuf:"bytes,1,opt,name=PId,proto3" json:"PId,omitempty"`          //玩家Id
	AddCoin int32  `protobuf:"varint,2,opt,name=AddCoin,proto3" json:"AddCoin,omitempty"` //添加金币
}

func (x *Net_Admin_AddPlayerCoinReq) Reset() {
	*x = Net_Admin_AddPlayerCoinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_AddPlayerCoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_AddPlayerCoinReq) ProtoMessage() {}

func (x *Net_Admin_AddPlayerCoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_AddPlayerCoinReq.ProtoReflect.Descriptor instead.
func (*Net_Admin_AddPlayerCoinReq) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *Net_Admin_AddPlayerCoinReq) GetPId() string {
	if x != nil {
		return x.PId
	}
	return ""
}

func (x *Net_Admin_AddPlayerCoinReq) GetAddCoin() int32 {
	if x != nil {
		return x.AddCoin
	}
	return 0
}

type Net_Admin_AddPlayerCoinRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret  int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`   //0:成功;1:失败;2:玩家不存在;
	Coin int32 `protobuf:"varint,2,opt,name=Coin,proto3" json:"Coin,omitempty"` //玩家金币
}

func (x *Net_Admin_AddPlayerCoinRet) Reset() {
	*x = Net_Admin_AddPlayerCoinRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_AddPlayerCoinRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_AddPlayerCoinRet) ProtoMessage() {}

func (x *Net_Admin_AddPlayerCoinRet) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_AddPlayerCoinRet.ProtoReflect.Descriptor instead.
func (*Net_Admin_AddPlayerCoinRet) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{18}
}

func (x *Net_Admin_AddPlayerCoinRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *Net_Admin_AddPlayerCoinRet) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

// 添加玩家钻石
type Net_Admin_AddPlayerGoldReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PId     string `protobuf:"bytes,1,opt,name=PId,proto3" json:"PId,omitempty"`          //玩家Id
	AddGold int32  `protobuf:"varint,2,opt,name=AddGold,proto3" json:"AddGold,omitempty"` //添加钻石
}

func (x *Net_Admin_AddPlayerGoldReq) Reset() {
	*x = Net_Admin_AddPlayerGoldReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_AddPlayerGoldReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_AddPlayerGoldReq) ProtoMessage() {}

func (x *Net_Admin_AddPlayerGoldReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_AddPlayerGoldReq.ProtoReflect.Descriptor instead.
func (*Net_Admin_AddPlayerGoldReq) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{19}
}

func (x *Net_Admin_AddPlayerGoldReq) GetPId() string {
	if x != nil {
		return x.PId
	}
	return ""
}

func (x *Net_Admin_AddPlayerGoldReq) GetAddGold() int32 {
	if x != nil {
		return x.AddGold
	}
	return 0
}

type Net_Admin_AddPlayerGoldRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret  int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`   //0:成功;1:失败;2:玩家不存在;
	Gold int32 `protobuf:"varint,2,opt,name=Gold,proto3" json:"Gold,omitempty"` //玩家金币
}

func (x *Net_Admin_AddPlayerGoldRet) Reset() {
	*x = Net_Admin_AddPlayerGoldRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_AddPlayerGoldRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_AddPlayerGoldRet) ProtoMessage() {}

func (x *Net_Admin_AddPlayerGoldRet) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_AddPlayerGoldRet.ProtoReflect.Descriptor instead.
func (*Net_Admin_AddPlayerGoldRet) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{20}
}

func (x *Net_Admin_AddPlayerGoldRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *Net_Admin_AddPlayerGoldRet) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

// 添加系统邮件->发送所有玩家
type Net_Admin_AddSystemEmailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PId     string `protobuf:"bytes,1,opt,name=PId,proto3" json:"PId,omitempty"`          //玩家Id
	AddGold int32  `protobuf:"varint,2,opt,name=AddGold,proto3" json:"AddGold,omitempty"` //添加钻石
}

func (x *Net_Admin_AddSystemEmailReq) Reset() {
	*x = Net_Admin_AddSystemEmailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_AddSystemEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_AddSystemEmailReq) ProtoMessage() {}

func (x *Net_Admin_AddSystemEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_AddSystemEmailReq.ProtoReflect.Descriptor instead.
func (*Net_Admin_AddSystemEmailReq) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{21}
}

func (x *Net_Admin_AddSystemEmailReq) GetPId() string {
	if x != nil {
		return x.PId
	}
	return ""
}

func (x *Net_Admin_AddSystemEmailReq) GetAddGold() int32 {
	if x != nil {
		return x.AddGold
	}
	return 0
}

type Net_Admin_AddSystemEmailRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret  int32 `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`   //0:成功;1:失败;2:玩家不存在;
	Gold int32 `protobuf:"varint,2,opt,name=Gold,proto3" json:"Gold,omitempty"` //玩家金币
}

func (x *Net_Admin_AddSystemEmailRet) Reset() {
	*x = Net_Admin_AddSystemEmailRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_admin_protocol_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Admin_AddSystemEmailRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Admin_AddSystemEmailRet) ProtoMessage() {}

func (x *Net_Admin_AddSystemEmailRet) ProtoReflect() protoreflect.Message {
	mi := &file_sys_admin_protocol_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Admin_AddSystemEmailRet.ProtoReflect.Descriptor instead.
func (*Net_Admin_AddSystemEmailRet) Descriptor() ([]byte, []int) {
	return file_sys_admin_protocol_proto_rawDescGZIP(), []int{22}
}

func (x *Net_Admin_AddSystemEmailRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *Net_Admin_AddSystemEmailRet) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

var File_sys_admin_protocol_proto protoreflect.FileDescriptor

var file_sys_admin_protocol_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x79, 0x73, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x5f, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x22, 0x5f, 0x0a, 0x15, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x5f, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a,
	0x09, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x28, 0x0a, 0x0f, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x4e, 0x75, 0x6d, 0x22, 0x18, 0x0a, 0x16, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x22,
	0x6b, 0x0a, 0x16, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x47, 0x65, 0x74,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x3f, 0x0a, 0x0a, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x70, 0x62, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x5f,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0a, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x17, 0x0a, 0x15,
	0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x22, 0x29, 0x0a, 0x15, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74,
	0x22, 0x1b, 0x0a, 0x19, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x22, 0x2d, 0x0a,
	0x19, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0x5e, 0x0a, 0x1c,
	0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f, 0x6c, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x22, 0x84, 0x01, 0x0a,
	0x1c, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12,
	0x28, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6f,
	0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x55, 0x73, 0x65,
	0x72, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x47, 0x6f, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x47,
	0x6f, 0x6c, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x19, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x5f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x47, 0x69, 0x66, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x47, 0x69, 0x66, 0x74, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x19, 0x4e, 0x65, 0x74, 0x5f, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0x2a, 0x0a, 0x28, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x64, 0x69, 0x73, 0x41,
	0x6c, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x22, 0x3c, 0x0a, 0x28, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x64, 0x69, 0x73, 0x41, 0x6c, 0x6c, 0x52, 0x6f,
	0x6c, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74,
	0x22, 0x14, 0x0a, 0x12, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x43, 0x68,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x22, 0x14, 0x0a, 0x12, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x5f, 0x43, 0x68, 0x65, 0x61, 0x74, 0x52, 0x65, 0x74, 0x22, 0x1c, 0x0a, 0x1a,
	0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x22, 0x1c, 0x0a, 0x1a, 0x4e, 0x65,
	0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x22, 0x48, 0x0a, 0x1a, 0x4e, 0x65, 0x74, 0x5f,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43,
	0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x43,
	0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x41, 0x64, 0x64, 0x43, 0x6f,
	0x69, 0x6e, 0x22, 0x42, 0x0a, 0x1a, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f,
	0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52,
	0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x22, 0x48, 0x0a, 0x1a, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x5f, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x47, 0x6f, 0x6c,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x50, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6c,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6c, 0x64,
	0x22, 0x42, 0x0a, 0x1a, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x41, 0x64,
	0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x47, 0x6f, 0x6c, 0x64, 0x52, 0x65, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x47, 0x6f, 0x6c, 0x64, 0x22, 0x49, 0x0a, 0x1b, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x5f, 0x41, 0x64, 0x64, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x50, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6c, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x41, 0x64, 0x64, 0x47, 0x6f, 0x6c, 0x64, 0x22,
	0x43, 0x0a, 0x1b, 0x4e, 0x65, 0x74, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x41, 0x64, 0x64,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x47, 0x6f, 0x6c, 0x64, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x62, 0x5f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sys_admin_protocol_proto_rawDescOnce sync.Once
	file_sys_admin_protocol_proto_rawDescData = file_sys_admin_protocol_proto_rawDesc
)

func file_sys_admin_protocol_proto_rawDescGZIP() []byte {
	file_sys_admin_protocol_proto_rawDescOnce.Do(func() {
		file_sys_admin_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_sys_admin_protocol_proto_rawDescData)
	})
	return file_sys_admin_protocol_proto_rawDescData
}

var file_sys_admin_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_sys_admin_protocol_proto_goTypes = []interface{}{
	(*Base_Admin_SystemInfo)(nil),                    // 0: pb_admin.Base_Admin_SystemInfo
	(*Net_Admin_GetSystemReq)(nil),                   // 1: pb_admin.Net_Admin_GetSystemReq
	(*Net_Admin_GetSystemRet)(nil),                   // 2: pb_admin.Net_Admin_GetSystemRet
	(*Net_Admin_GetUsersReq)(nil),                    // 3: pb_admin.Net_Admin_GetUsersReq
	(*Net_Admin_GetUsersRet)(nil),                    // 4: pb_admin.Net_Admin_GetUsersRet
	(*Net_Admin_UpdateConfigReq)(nil),                // 5: pb_admin.Net_Admin_UpdateConfigReq
	(*Net_Admin_UpdateConfigRet)(nil),                // 6: pb_admin.Net_Admin_UpdateConfigRet
	(*Net_Admin_UserAddCurrencyReq)(nil),             // 7: pb_admin.Net_Admin_UserAddCurrencyReq
	(*Net_Admin_UserAddCurrencyRet)(nil),             // 8: pb_admin.Net_Admin_UserAddCurrencyRet
	(*Net_Admin_ExecuteEmailReq)(nil),                // 9: pb_admin.Net_Admin_ExecuteEmailReq
	(*Net_Admin_ExecuteEmailRet)(nil),                // 10: pb_admin.Net_Admin_ExecuteEmailRet
	(*Net_Admin_DeleteRedisAllRoleCacheDataReq)(nil), // 11: pb_admin.Net_Admin_DeleteRedisAllRoleCacheDataReq
	(*Net_Admin_DeleteRedisAllRoleCacheDataRet)(nil), // 12: pb_admin.Net_Admin_DeleteRedisAllRoleCacheDataRet
	(*Net_Admin_CheatReq)(nil),                       // 13: pb_admin.Net_Admin_CheatReq
	(*Net_Admin_CheatRet)(nil),                       // 14: pb_admin.Net_Admin_CheatRet
	(*Net_Admin_DeleteAccountReq)(nil),               // 15: pb_admin.Net_Admin_DeleteAccountReq
	(*Net_Admin_DeleteAccountRet)(nil),               // 16: pb_admin.Net_Admin_DeleteAccountRet
	(*Net_Admin_AddPlayerCoinReq)(nil),               // 17: pb_admin.Net_Admin_AddPlayerCoinReq
	(*Net_Admin_AddPlayerCoinRet)(nil),               // 18: pb_admin.Net_Admin_AddPlayerCoinRet
	(*Net_Admin_AddPlayerGoldReq)(nil),               // 19: pb_admin.Net_Admin_AddPlayerGoldReq
	(*Net_Admin_AddPlayerGoldRet)(nil),               // 20: pb_admin.Net_Admin_AddPlayerGoldRet
	(*Net_Admin_AddSystemEmailReq)(nil),              // 21: pb_admin.Net_Admin_AddSystemEmailReq
	(*Net_Admin_AddSystemEmailRet)(nil),              // 22: pb_admin.Net_Admin_AddSystemEmailRet
}
var file_sys_admin_protocol_proto_depIdxs = []int32{
	0, // 0: pb_admin.Net_Admin_GetSystemRet.SystemInfo:type_name -> pb_admin.Base_Admin_SystemInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sys_admin_protocol_proto_init() }
func file_sys_admin_protocol_proto_init() {
	if File_sys_admin_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sys_admin_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Base_Admin_SystemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_GetSystemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_GetSystemRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_GetUsersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_GetUsersRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_UpdateConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_UpdateConfigRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_UserAddCurrencyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_UserAddCurrencyRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_ExecuteEmailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_ExecuteEmailRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_DeleteRedisAllRoleCacheDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_DeleteRedisAllRoleCacheDataRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_CheatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_CheatRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_DeleteAccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_DeleteAccountRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_AddPlayerCoinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_AddPlayerCoinRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_AddPlayerGoldReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_AddPlayerGoldRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_AddSystemEmailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_admin_protocol_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Admin_AddSystemEmailRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sys_admin_protocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_admin_protocol_proto_goTypes,
		DependencyIndexes: file_sys_admin_protocol_proto_depIdxs,
		MessageInfos:      file_sys_admin_protocol_proto_msgTypes,
	}.Build()
	File_sys_admin_protocol_proto = out.File
	file_sys_admin_protocol_proto_rawDesc = nil
	file_sys_admin_protocol_proto_goTypes = nil
	file_sys_admin_protocol_proto_depIdxs = nil
}
