// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.23.1
// source: pbs_global.proto

package pbs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 内部转发Common
type Net_Global_RPCGameWorldReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetId    string `protobuf:"bytes,1,opt,name=NetId,proto3" json:"NetId,omitempty"`       //也是 IPAddress地址
	UserId   string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`     //
	ReqId    int32  `protobuf:"varint,5,opt,name=ReqId,proto3" json:"ReqId,omitempty"`      //转发消息1001002
	ReqBytes []byte `protobuf:"bytes,6,opt,name=ReqBytes,proto3" json:"ReqBytes,omitempty"` //消息内容
}

func (x *Net_Global_RPCGameWorldReq) Reset() {
	*x = Net_Global_RPCGameWorldReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbs_global_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Global_RPCGameWorldReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Global_RPCGameWorldReq) ProtoMessage() {}

func (x *Net_Global_RPCGameWorldReq) ProtoReflect() protoreflect.Message {
	mi := &file_pbs_global_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Global_RPCGameWorldReq.ProtoReflect.Descriptor instead.
func (*Net_Global_RPCGameWorldReq) Descriptor() ([]byte, []int) {
	return file_pbs_global_proto_rawDescGZIP(), []int{0}
}

func (x *Net_Global_RPCGameWorldReq) GetNetId() string {
	if x != nil {
		return x.NetId
	}
	return ""
}

func (x *Net_Global_RPCGameWorldReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Net_Global_RPCGameWorldReq) GetReqId() int32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *Net_Global_RPCGameWorldReq) GetReqBytes() []byte {
	if x != nil {
		return x.ReqBytes
	}
	return nil
}

type Net_Global_RPCGameWorldRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateCid   string `protobuf:"bytes,1,opt,name=GateCid,proto3" json:"GateCid,omitempty"` //也是 IPAddress地址
	Cid       string `protobuf:"bytes,2,opt,name=Cid,proto3" json:"Cid,omitempty"`
	IPAddress string `protobuf:"bytes,3,opt,name=IPAddress,proto3" json:"IPAddress,omitempty"`
	UserId    string `protobuf:"bytes,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ReqId     int32  `protobuf:"varint,5,opt,name=ReqId,proto3" json:"ReqId,omitempty"`      //转发消息1001002
	ReqBytes  []byte `protobuf:"bytes,6,opt,name=ReqBytes,proto3" json:"ReqBytes,omitempty"` //消息内容
}

func (x *Net_Global_RPCGameWorldRet) Reset() {
	*x = Net_Global_RPCGameWorldRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbs_global_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Global_RPCGameWorldRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Global_RPCGameWorldRet) ProtoMessage() {}

func (x *Net_Global_RPCGameWorldRet) ProtoReflect() protoreflect.Message {
	mi := &file_pbs_global_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Global_RPCGameWorldRet.ProtoReflect.Descriptor instead.
func (*Net_Global_RPCGameWorldRet) Descriptor() ([]byte, []int) {
	return file_pbs_global_proto_rawDescGZIP(), []int{1}
}

func (x *Net_Global_RPCGameWorldRet) GetGateCid() string {
	if x != nil {
		return x.GateCid
	}
	return ""
}

func (x *Net_Global_RPCGameWorldRet) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Net_Global_RPCGameWorldRet) GetIPAddress() string {
	if x != nil {
		return x.IPAddress
	}
	return ""
}

func (x *Net_Global_RPCGameWorldRet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Net_Global_RPCGameWorldRet) GetReqId() int32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *Net_Global_RPCGameWorldRet) GetReqBytes() []byte {
	if x != nil {
		return x.ReqBytes
	}
	return nil
}

var File_pbs_global_proto protoreflect.FileDescriptor

var file_pbs_global_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x73, 0x5f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x70, 0x62, 0x73, 0x22, 0x7c, 0x0a, 0x1a, 0x4e, 0x65, 0x74, 0x5f, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x52, 0x50, 0x43, 0x47, 0x61, 0x6d, 0x65, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4e, 0x65, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x71, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x52, 0x65, 0x71, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x71,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x52, 0x65, 0x71,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0xb0, 0x01, 0x0a, 0x1a, 0x4e, 0x65, 0x74, 0x5f, 0x47, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x52, 0x50, 0x43, 0x47, 0x61, 0x6d, 0x65, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x52, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x61, 0x74, 0x65, 0x43, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x61, 0x74, 0x65, 0x43, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x43, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43, 0x69, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x49, 0x50, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x50, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x71, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x65, 0x71, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x65, 0x71, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x52, 0x65, 0x71, 0x42, 0x79, 0x74, 0x65, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x70, 0x62,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbs_global_proto_rawDescOnce sync.Once
	file_pbs_global_proto_rawDescData = file_pbs_global_proto_rawDesc
)

func file_pbs_global_proto_rawDescGZIP() []byte {
	file_pbs_global_proto_rawDescOnce.Do(func() {
		file_pbs_global_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbs_global_proto_rawDescData)
	})
	return file_pbs_global_proto_rawDescData
}

var file_pbs_global_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbs_global_proto_goTypes = []interface{}{
	(*Net_Global_RPCGameWorldReq)(nil), // 0: pbs.Net_Global_RPCGameWorldReq
	(*Net_Global_RPCGameWorldRet)(nil), // 1: pbs.Net_Global_RPCGameWorldRet
}
var file_pbs_global_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbs_global_proto_init() }
func file_pbs_global_proto_init() {
	if File_pbs_global_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbs_global_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Global_RPCGameWorldReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbs_global_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Global_RPCGameWorldRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbs_global_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbs_global_proto_goTypes,
		DependencyIndexes: file_pbs_global_proto_depIdxs,
		MessageInfos:      file_pbs_global_proto_msgTypes,
	}.Build()
	File_pbs_global_proto = out.File
	file_pbs_global_proto_rawDesc = nil
	file_pbs_global_proto_goTypes = nil
	file_pbs_global_proto_depIdxs = nil
}
