// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.23.1
// source: sys_server_protocol.proto

package pbs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 内部消息包请求
type Net_InternalMessagePacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType int32  `protobuf:"varint,1,opt,name=MsgType,proto3" json:"MsgType,omitempty"` //1:MT_NET_RECV_MSG 2:MT_NET_DISCONNECT_NOTICE
	NetId   string `protobuf:"bytes,2,opt,name=NetId,proto3" json:"NetId,omitempty"`      //也是 IPAddress地址
	UserId  string `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`    //用户Id
	MsgId   int32  `protobuf:"varint,4,opt,name=MsgId,proto3" json:"MsgId,omitempty"`     //RetId转发消息1001002
	MsgData []byte `protobuf:"bytes,5,opt,name=MsgData,proto3" json:"MsgData,omitempty"`  //ReqBytes消息内容
}

func (x *Net_InternalMessagePacket) Reset() {
	*x = Net_InternalMessagePacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_server_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_InternalMessagePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_InternalMessagePacket) ProtoMessage() {}

func (x *Net_InternalMessagePacket) ProtoReflect() protoreflect.Message {
	mi := &file_sys_server_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_InternalMessagePacket.ProtoReflect.Descriptor instead.
func (*Net_InternalMessagePacket) Descriptor() ([]byte, []int) {
	return file_sys_server_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Net_InternalMessagePacket) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *Net_InternalMessagePacket) GetNetId() string {
	if x != nil {
		return x.NetId
	}
	return ""
}

func (x *Net_InternalMessagePacket) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Net_InternalMessagePacket) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *Net_InternalMessagePacket) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

var File_sys_server_protocol_proto protoreflect.FileDescriptor

var file_sys_server_protocol_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x79, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x62, 0x73,
	0x22, 0x93, 0x01, 0x0a, 0x19, 0x4e, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x65, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4e, 0x65, 0x74, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x4d,
	0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x70, 0x62, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sys_server_protocol_proto_rawDescOnce sync.Once
	file_sys_server_protocol_proto_rawDescData = file_sys_server_protocol_proto_rawDesc
)

func file_sys_server_protocol_proto_rawDescGZIP() []byte {
	file_sys_server_protocol_proto_rawDescOnce.Do(func() {
		file_sys_server_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_sys_server_protocol_proto_rawDescData)
	})
	return file_sys_server_protocol_proto_rawDescData
}

var file_sys_server_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sys_server_protocol_proto_goTypes = []interface{}{
	(*Net_InternalMessagePacket)(nil), // 0: pbs.Net_InternalMessagePacket
}
var file_sys_server_protocol_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sys_server_protocol_proto_init() }
func file_sys_server_protocol_proto_init() {
	if File_sys_server_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sys_server_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_InternalMessagePacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sys_server_protocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_server_protocol_proto_goTypes,
		DependencyIndexes: file_sys_server_protocol_proto_depIdxs,
		MessageInfos:      file_sys_server_protocol_proto_msgTypes,
	}.Build()
	File_sys_server_protocol_proto = out.File
	file_sys_server_protocol_proto_rawDesc = nil
	file_sys_server_protocol_proto_goTypes = nil
	file_sys_server_protocol_proto_depIdxs = nil
}
