// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.1
// source: sys_server_protocol.proto

package pbs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 内部消息包请求
type Net_InternalMessagePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       int32                  `protobuf:"varint,1,opt,name=MsgType,proto3" json:"MsgType,omitempty"` //1:MT_NET_RECV_MSG 2:MT_NET_DISCONNECT_NOTICE
	NetId         string                 `protobuf:"bytes,2,opt,name=NetId,proto3" json:"NetId,omitempty"`      //也是 IPAddress地址
	UserId        string                 `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`    //用户Id
	MsgId         int32                  `protobuf:"varint,4,opt,name=MsgId,proto3" json:"MsgId,omitempty"`     //RetId转发消息1001002
	MsgData       []byte                 `protobuf:"bytes,5,opt,name=MsgData,proto3" json:"MsgData,omitempty"`  //ReqBytes消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Net_InternalMessagePacket) Reset() {
	*x = Net_InternalMessagePacket{}
	mi := &file_sys_server_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Net_InternalMessagePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_InternalMessagePacket) ProtoMessage() {}

func (x *Net_InternalMessagePacket) ProtoReflect() protoreflect.Message {
	mi := &file_sys_server_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_InternalMessagePacket.ProtoReflect.Descriptor instead.
func (*Net_InternalMessagePacket) Descriptor() ([]byte, []int) {
	return file_sys_server_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Net_InternalMessagePacket) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *Net_InternalMessagePacket) GetNetId() string {
	if x != nil {
		return x.NetId
	}
	return ""
}

func (x *Net_InternalMessagePacket) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Net_InternalMessagePacket) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *Net_InternalMessagePacket) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

var File_sys_server_protocol_proto protoreflect.FileDescriptor

const file_sys_server_protocol_proto_rawDesc = "" +
	"\n" +
	"\x19sys_server_protocol.proto\x12\x03pbs\"\x93\x01\n" +
	"\x19Net_InternalMessagePacket\x12\x18\n" +
	"\aMsgType\x18\x01 \x01(\x05R\aMsgType\x12\x14\n" +
	"\x05NetId\x18\x02 \x01(\tR\x05NetId\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\tR\x06UserId\x12\x14\n" +
	"\x05MsgId\x18\x04 \x01(\x05R\x05MsgId\x12\x18\n" +
	"\aMsgData\x18\x05 \x01(\fR\aMsgDataB\aZ\x05./pbsb\x06proto3"

var (
	file_sys_server_protocol_proto_rawDescOnce sync.Once
	file_sys_server_protocol_proto_rawDescData []byte
)

func file_sys_server_protocol_proto_rawDescGZIP() []byte {
	file_sys_server_protocol_proto_rawDescOnce.Do(func() {
		file_sys_server_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sys_server_protocol_proto_rawDesc), len(file_sys_server_protocol_proto_rawDesc)))
	})
	return file_sys_server_protocol_proto_rawDescData
}

var file_sys_server_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sys_server_protocol_proto_goTypes = []any{
	(*Net_InternalMessagePacket)(nil), // 0: pbs.Net_InternalMessagePacket
}
var file_sys_server_protocol_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sys_server_protocol_proto_init() }
func file_sys_server_protocol_proto_init() {
	if File_sys_server_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sys_server_protocol_proto_rawDesc), len(file_sys_server_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_server_protocol_proto_goTypes,
		DependencyIndexes: file_sys_server_protocol_proto_depIdxs,
		MessageInfos:      file_sys_server_protocol_proto_msgTypes,
	}.Build()
	File_sys_server_protocol_proto = out.File
	file_sys_server_protocol_proto_goTypes = nil
	file_sys_server_protocol_proto_depIdxs = nil
}
