#需要翻墙下载 就需要在本地下载好 在Copy到远端Docker->images里
#正式服部署 Ubuntu 22.04
services:  # 定义所有需要运行的服务
  redis:  # redis 服务
    image: redis:latest  # 使用最新的 redis 镜像
    platform: linux/amd64  # 明确指定镜像架构为 x86_64
    container_name: redis_6376  # 容器名称，方便管理
    ports:
      - "63792:6379"  # 将主机63791端口映射到容器6379端口
    volumes:
      - ./ricebean_data/redis_data:/data  # 挂载主机目录到容器，实现数据持久化
    command: redis-server --port 6376 --save 900 1 --save 300 10 --save 60 10000  # 启动 redis 并设置持久化策略
    restart: unless-stopped  # 容器异常退出时自动重启，除非手动停止
    networks:
      - ricebean_network  # 连接到 ricebean_network 网络，便于与其他服务通信

volumes:
  redis_data:  # 定义 redis_data 卷，用于持久化存储
    driver: local  # 使用本地驱动

networks:
  ricebean_network:
    driver: bridge
